### ISSUE TITLE
Invoke command not found in M3 environment

### ISSUE THREAD

**Issue by yenyee912** [pyinvoke/invoke#1003]
Hi I got the issue of command not found: invoke, but I indeed installing invoke instead of pyinvoke, when I reinstall again, I got this message:

> Requirement already satisfied: invoke in /Users/xxx/Library/Python/3.9/lib/python/site-packages (2.2.0)

Anyone have a clue please? 
P/s: This command works well on Intel Mac, I just migrated from my old env.

**Comment by NotizMe** [comment]
Some extra information would be nice. See: https://www.contribution-guide.org/#what-to-put-in-your-bug-report

Some remarks that come to mind:
- Please specify how you installed Invoke.
- Can you reproduce the problem ?  Please provide the steps for reproducing the problem.
- What is the output of
  - `python --version` ?
  - `python3 --version` ?
  - `invoke --version` ?
  - `whereis python` ?

**Comment by yenyee912** [comment]
Hi, I have solved the issue, it was the Python3 path somehow unaccessible by the env as M3 always need chmod, thanks!
