### ISSUE TITLE
Expanded configuration mechanisms

### ISSUE THREAD

**Issue by sophacles** [pyinvoke/invoke#147]
## Maintainer edits

Overall TODO generated by huge arse discussion thread.

* [x] Add new concepts doc on configuration, including a clearly marked hierarchy definition, and a big WARNING about how multiple files in same location w/ diff extensions are not merged.
* [x] Make sure to clarify `.yaml`, not `.yml`.
* [x] ~~Probably also needs an update to the CLI docs section re: flags and env vars (new subsection)~~ *punting on user-driven config updates that aren't env vars; env vars have their own section in config so no need to duplicate*
* [x] ~~Re: env vars, need to figure out best way for user-driven config settings to work too, eventually~~ *punting*
* [x] ~~Brief mention of concepts doc in the tutorial~~ *Actually don't see an elegant way to work it in - feels best just as a standalone regular concepts doc for now*
* [x] Make sure API in docs gets updated to be consistent & 'modern' - e.g. `obj['foo.bar']` should turn into `obj['foo']['bar']` or ideally with the option of `obj.foo.bar`.
* [x] Update `concepts/contexts` to adapt, possibly paring it way down or removing entirely, tl;dr it's just about explaining how contexts perform shared state.
    * The 'nested collection configs get merged' explanation could still live here but probably lives better in the new config page, or the namespacing page if it exists.
* [x] Vendorize `etcaetera`
* [x] Use its `Config` object in place of `Context`'s existing inner dicts, get tests passing again referencing it (it's dict-like).
    * Decide whether the current run/general/etc splits become sub-config objects or just nested namespaces within the primary config object
    * Leaning towards the latter so people can override them everywhere
* [x] Add new CLI flags for setting config options (primarily `-f` or whatnot for "specific config file")
* [x] Implement hierarchy re: multiple conf files + env vars + ~~cli flags~~ + in-module configs
* [x] Conf file loading of different extensions at the same 'location' is exclusive - no merging of eg `/etc/invoke.yaml` and `/etc/invoke.json`.
* [x] Debugging of conf option overrides must be easy
    * either via a no-op CLI flag showing what the tree would be for a given task module (or task invocation?), or
    * via regular debug output (ideally + a no-op option)
    * really, those go to the same place
* [x] If not covered in the previous point: it must be easy to troubleshoot stupid typos in config file paths.
    * e.g. if you accidentally created a `/etc/invok.yaml`, or fatfingered the arg to `invoke -f <path>` - it should be clear when running with `-d` which config files it attempted to load and which ones failed to load.
    * Main problem is that for the first 3-4 levels we have 3x file paths we end up searching for, so it will be somewhat verbose :( but no obvious solution offhand, better to add it to debug output (or some other level?) than try to be clever.
* [x] Update invocations to use this new setup instead of dotted names - they still technically *work* but are invalid for eg env var translation.
* [ ] `Context` objects (& subclasses like Fabric2's `Connection`) need a clean API for this configuration stuff - either `Context` directly grows all the config related methods (perhaps becoming a `etcaetera.Config` subclass itself?) or it accepts some config object (again perhaps `etc.Config`) as an instance member.
    * The current driving need here is actually testing related, I need to inject a config value override or two in `Connection` tests.
* [ ] Fill in any remaining skipped tests related to this feature set.

----

## Original ticket description from sophacles

It would be nice to be able to pass context variables on the command line to invoke scripts. Something like:

```
> inv -X var1=val1 -Xvar2=val2 target --target1opt=val
```

And perhaps even allow targeting variables to specific namespaces, ala:
```
inv -X ns1.var1=val1 -Xvar2=val2 ns1.target  target2
```
for those cases where `target2` should use the default for var1, but ns.target1 needs the overridden value.

There are of course concerns about how command line set options override things in a call to `Collection.configure`... take for instance this script:

```
@ctask
def task1(ctx):
      run("echo {val1}".format(**ctx.config))

@ctask
def task2(ctx):
    run("echo {var1} and {var2}".format(**ctx.config))

ns1 = Collection(task1)
ns1.configure({"var1":"ns1var1"})
ns = Collection(ns, task2)
ns.configure({"var1":"globalvar1","var2":"globalvar2"})
```

Which is the right output:

*option 1*:
```
# inv -X ns1.var1=clival1 -X var2=clivar2 ns1.task1 task2
clival1
globalvar1 and clivar2
```
*(note - because generally it's considered cli options override anything in-program)*

*option 2:*
```
# inv -X ns1.var1=clival1 -X var2=clivar2 ns1.task1 task2
globalvar1
globalvar1 and clivar2
```
*(note because of the way overrides work in invoke already)*

I think everyone would agree that:
```
# inv -X var1=clival1 ns1.task task.2
clival1
clival1 and globalvar2
```
is correct.

**Comment by sophacles** [comment]
W00t!!

**Comment by bitprophet** [comment]
I haven't actually finished the Fab 2 integration but I figured any changes would be minimal and was not worth having this mega huge branch floating outside master :) whee.

**Comment by pieterlukasse** [comment]
Hi, what is the conclusion regarding 
```
inv -X var1=clival1 ns1.task task.2
```
I am struggling to find what is the current way of setting global arguments that are valid for all tasks.
Thanks!

**Comment by TaiSHiNet** [comment]
@pieterlukasse I believe this is being followed on #153 
Although, namespaces/collections can have configs, you would still have to define (as of now) the parameters on every task

**Comment by LecrisUT** [comment]
> - [ ]  Context objects (& subclasses like Fabric2's Connection) need a clean API for this configuration stuff - either Context directly grows all the config related methods (perhaps becoming a etcaetera.Config subclass itself?) or it accepts some config object (again perhaps etc.Config) as an instance member.
>
>    - The current driving need here is actually testing related, I need to inject a config value override or two in Connection tests.


@sophacles are there any linked issues for this?

**Comment by sophacles** [comment]
Hi @LecrisUT - I don't think there are. I've forgotten most of the context (pun not intended) around this at this point, and any issues I would have linked to it went away when the startup I was working for at the time closed down.
