### ISSUE TITLE
I want to change to tasks file name to others, not tasks.py. But seems not allow.

### ISSUE THREAD

**Issue by hackrole** [pyinvoke/invoke#151]
hello, I use invoke in a django web app. And also I need to use celery. both use the file named tasks.py. the celery can be changed to other, but not the invoke.

I think this is a needed options to let user to give the file name to load tasks while running?

but I go through the source found there just no way to do so.

so what's you consider for this? any good practice for this situation?

**Comment by sar009** [comment]
you can also try importing the task in `__init__.py`.
