### ISSUE TITLE
Context managers coming to Invoke, or remaining in Fabric?

### ISSUE THREAD

**Issue by gotgenes** [pyinvoke/invoke#172]
Are `lcd` and other [context managers](http://docs.fabfile.org/en/1.9/api/core/context_managers.html) coming to Invoke, or will those be remaining as part of the Fabric API? I see right now there is a `invoke.context` module, but it currently only contains a generic `Context` class.

**Comment by kottenator** [comment]
Any updates on this issue? 
Invoke is really great but I need 2 more things (back from Fabric): `cd` and `prefix`. 
Or can I already do this via `@ctask` context?

**Comment by gotgenes** [comment]
See also #230.

**Comment by kottenator** [comment]
OK, I would gladly do it in "correct way", I just want to know - how should I do this? Is it possible via `@ctask`? I would appreciate an example

**Comment by bitprophet** [comment]
@kottenator Haven't put those in yet but still plan to (still soon, but actually soon, as a fabric 2 alpha is imminent and having those is one of the first things to add after bare minimum functionality).

I assume you mean specifically the contextmanager aspect; I will note that `os.chdir` totally works in my setup, for changing the cwd of `run()` calls.
