### ISSUE TITLE
run() does not raise Failure Exception

### ISSUE THREAD

**Issue by rumpelsepp** [pyinvoke/invoke#193]
From the docs:

> A Failure exception (containing a reference to the Result that would otherwise have been returned) is raised if the command terminates with a nonzero return code. This behavior may be disabled by setting warn=True.

This task:

``` python
@task
def load_module():
    run('sudo -v')
    print('Loading module...')
    run('sudo modprobe my_non_existing_module')
    print('Module does not exist!')
```

Does not raise the `Failure` Exception as it is described in the docs. It just terminates silently after `run()`. The last `print()` is not executed:

```
$ invoke load_module
Loading module...
modprobe: WARNING: Module my_non_existing_module not found.
```

I have modified the code a bit to do further research:

``` python
@task
def load_module():
    from pprint import pprint
    run('sudo -v')
    print('Loading module...')
    r =  run('sudo modprobe my_non_existing_module', warn=True')
    pprint(vars(r))
    print('Module does not exist!')
```

I get this:

```
$ invoke load_module
Loading module...
modprobe: WARNING: Module my_non_existing_module not found.
{'exception': None,
 'exited': 1,
 'pty': False,
 'return_code': 1,
 'stderr': 'modprobe: WARNING: Module my_non_existing_module not found.\n'
 'stdout': ''}
Module does not exist!
```

As we can see the return code is `1` so the `Failure` Exception should be raised, shouldn't it?

**Comment by code-tree** [comment]
One downside to this is that commands like "git grep", when it has no matches, returns an error code of "1" but prints nothing to stderr. This has been silently exiting mid-task for me, when it looked like the whole task succeeded.

Is it possible to include a setting for invoke to print something if it exits with an error? I agree that it should be optional only though.
