### ISSUE TITLE
No task to build invoke itself

### ISSUE THREAD

**Issue by techtonik** [pyinvoke/invoke#203]
I expected to see an example how to build `invoke` distribution for upload, but there is nothing.

**Comment by sophacles** [comment]
Two things here... 

1. The pyinvoke user has another repo called invocations. ( https://github.com/pyinvoke/invocations ) This repo has a taskfile - invocations/packaging that does this.

2. The tools invoke uses to do this are python and setuptools - just standard python tools for distribution (etc). Nothing fancy or custom.

**Comment by bitprophet** [comment]
What @sophacles said! If that doesn't answer your question then please clarify :) Thanks!

**Comment by techtonik** [comment]
In short, I don't want to `install` or `compile` development version of invoke in order to use it, so I thought that current source layout supports it, but apparently, it doesn't, and there is no instruction how to compile it, so I don't know how to fix that. My wish for `checkout and run`.

**Comment by sophacles** [comment]
@techtonik to be fair - python development best practices have stabilized the last few years to:

1. checkout source
2. create a virtualenv, and activate it.
3. in the source directory `pip install -e .`
4. use and modify the package at will within the virtualenv

This method works just fine for `invoke`.

(also to run tests by hand, you just `pip install tox` from within your virtualenv, and then do `tox` from the source root dir (the one containing the `tox.ini` file)

**Comment by techtonik** [comment]
@sophacles, how about just checkout&run, is it considered a bad practice for 2015 or `invoke`?

1.checkout source
2.run bootstrap.py (or demo.py)

https://bitbucket.org/spyder-ide/spyderlib#markdown-header-running-from-source
https://bitbucket.org/scons/scons/src#rst-header-executing-scons-without-installing
https://bitbucket.org/roundup/roundup/src#rst-header-instant-gratification

**Comment by techtonik** [comment]
> python development best practices have stabilized the last few years to:

I should abandon this platform. Nobody uses it anyway for any real work. Go is the future.
