### ISSUE TITLE
tasks.py: watch command uses "sys" module without import 

### ISSUE THREAD

**Issue by jenisys** [pyinvoke/invoke#206]
By inspection of the main "tasks.py" (verified with head of git repository).

**Comment by gtback** [comment]
I think this was fixed by #212 (see [here](https://github.com/pyinvoke/invoke/pull/212/files#diff-dc31105b816206de63c47bf42ec2a4d7R2)).

**Comment by bitprophet** [comment]
Yea that was probably a temporary oops, thanks for checking/bumping, @gtback .
