### ISSUE TITLE
invoke hides stdouts

### ISSUE THREAD

**Issue by learner010** [pyinvoke/invoke#209]
I have following tasks
```python
@task
def quick_test():
    run("REUSE_DB=0 python manage.py test")

@task
def shell():
    run("python manage.py shell")
```

The problem is invoke suppresses some of its outputs. Like `$ REUSE_DB=0 python manage.py test` confirms if I wish to remove earlier test db is exists. But using the task above suppresses the confirmation message.

The shell task also hides `>>>` and up, right, back and left keys doesn't work.

Is there any flag to prevent this?

**Comment by buz-zard** [comment]
I have the same issue on windows.

**Comment by sophacles** [comment]
Don't know about windows, but on my Mac and Linux installs, running with `pty=True` works. Like this:

```python
from invoke import run, task

@task
def atask():
    run("python", pty=True)
```

The `pty=True` tells (eventually) the OS to output as if to a terminal, rather than just a text stream, for `stdin` and `stdout`.

**Comment by buz-zard** [comment]
Windows doesn't have `pty` at all, I'm not sure if stdout is supported at all on Windows. On Ubuntu I can run commands without `pty=True` and can see the output successfully.

**Comment by sophacles** [comment]
@buz-zard - sorry my comment wasn't super clear - the problem @learner010 is facing (if it's on osx or linux) can be addressed via the `pty=True` argurment. As for the problem you're facing with windows - work on that is happening in #201

**Comment by learner010** [comment]
@sophacles  Thanx that solves the problem. But I am curious why isn't it the default setting?
