### ISSUE TITLE
Documentation: the example for configuration raises an AttributeError

### ISSUE THREAD

**Issue by mlindemann** [pyinvoke/invoke#210]
Page http://docs.pyinvoke.org/en/latest/concepts/configuration.html, the following code example...

```python
from invoke import Collection, ctask as task

@task
def clean(ctx, target=None):
    ctx.run("rm -rf {0}".format(target or ctx.sphinx.target))

@task
def build(ctx, target=None):
    ctx.run("sphinx-build docs {0}".format(target or ctx.sphinx.target))

ns = Collection(clean, build)
ns.configure({'sphinx': {'target': "docs/_build"}})
```
... returns: `AttributeError: 'Context' object has no attribute 'sphinx'`

**Comment by jenisys** [comment]
Which version of ``invoke`` are you using ?
I first used invoke-0.9.0 from pypi and ran into similar problems.
When I used the Github repository tip (which also says its version is 0.9.0), the problems were gone. 
NOTE: I am not quite sure if they are completely gone, but they are solved in most cases.

**Comment by mlindemann** [comment]
I was using the pypi version.

Now, I have followed your advice and installed from Git.

Configuring by namespace works, i.e. the code below executes properly:

```python
from invoke import Collection, ctask as task

@task
def clean(ctx, target=None):
    ctx.run("echo CLEANING {0}".format(target or ctx.sphinx.target))

@task
def build(ctx, target=None):
    ctx.run("echo BUILDING {0}".format(target or ctx.sphinx.target))

ns = Collection(clean, build)
ns.configure({'sphinx': {'target': "docs/_build"}})
```

But configuring by invoke.yaml or invoke.py files still raises an error:

```python
# file: .../deploy_tools/tasks.py
from invoke import Collection, ctask as task

@task
def clean(ctx, target=None):
    ctx.run("echo CLEANING {0}".format(target or ctx.sphinx.target))

@task
def build(ctx, target=None):
    ctx.run("echo BUILDING {0}".format(target or ctx.sphinx.target))

ns = Collection(clean, build)
#ns.configure({'sphinx': {'target': "docs/_build"}})
```
```yaml
# file: .../deploy_tools/invoke.yaml
sphinx:
    target: built_docs
```

```bash
$ invoke clean
Traceback (most recent call last):
  File "/data/webapps/tdd/invoke-master/invoke/config.py", line 55, in __getattr__
    return self._get(key)
  File "/data/webapps/tdd/invoke-master/invoke/config.py", line 97, in _get
    value = self.config[key]
  File "/data/webapps/tdd/invoke-master/invoke/config.py", line 94, in __getitem__
    return self._get(key)
  File "/data/webapps/tdd/invoke-master/invoke/config.py", line 97, in _get
    value = self.config[key]
KeyError: 'sphinx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/webapps/tdd/env/bin/invoke", line 9, in <module>
    load_entry_point('invoke==0.9.0', 'console_scripts', 'invoke')()
  File "/data/webapps/tdd/invoke-master/invoke/cli.py", line 352, in main
    dispatch(sys.argv)
  File "/data/webapps/tdd/invoke-master/invoke/cli.py", line 345, in dispatch
    return executor.execute(*tasks)
  File "/data/webapps/tdd/invoke-master/invoke/executor.py", line 98, in execute
    task=task, name=name, args=args, kwargs=kwargs, config=config
  File "/data/webapps/tdd/invoke-master/invoke/executor.py", line 148, in _execute
    result = task(*args, **kwargs)
  File "/data/webapps/tdd/invoke-master/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/data/webapps/tdd/deploy_tools/tasks.py", line 5, in clean
    ctx.run("echo CLEANING {0}".format(target or ctx.sphinx.target))
  File "/data/webapps/tdd/invoke-master/invoke/config.py", line 65, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'sphinx'

Valid keys: ['run', 'tasks']

Valid real attributes: ['from_data', 'run']
```

**Comment by bitprophet** [comment]
Two quick things:

1. The docs at /en/latest always apply to git, as you've found. I just poked at our doc host to make sure it's defaulting to the latest stable version instead of 'latest', though - that was an oversight on our part.
1. I tested out the new config stuff a bunch, but it's not in the wild yet so this might be a legitimate bug, I will set aside time to verify in the near future. Thanks!

**Comment by gtback** [comment]
I am seeing the same behavior as @mlindemann (using current master - c61f1bd1093b564b68babc0b95d4fd9be2fdd0fe). 

I have a tasks.py with the same content. When the `ns.configure({'sphinx': {'target': "docs/_build"}})` line is uncommented, both `inv build` and `inv clean` work as expected; so does passing a custom `target` with the `-t` flag. 

Once I comment out the line, and add the corresponding `invoke.yaml` file, `inv clean` and `inv build` raise the same error as @mlindemann:

```
AttributeError: No attribute or config key found for 'sphinx'

Valid keys: ['run', 'tasks']

Valid real attributes: ['from_data', 'run']
```

I **am** able to explicitly pass the file name with the `-f` flag, (i.e. `inv -f invoke.yaml clean` *does* work). This is my first time looking at the Invoke code, but I'll see if I can track down why this is happening.

**Comment by gtback** [comment]
From what I've been able to tell, the code [here](https://github.com/pyinvoke/invoke/blob/c61f1bd1093b564b68babc0b95d4fd9be2fdd0fe/invoke/config.py#L321-L333) does not have a `project_home` set, so none of those variables get set and `_load_file` exits [here](https://github.com/pyinvoke/invoke/blob/c61f1bd1093b564b68babc0b95d4fd9be2fdd0fe/invoke/config.py#L467) because `_project_prefix` is `None`.

I'm not sure the best place to fix this, however. I'll look more into how the loader works and how the `Config` object gets instantiated tomorrow if I get a chance.

**Comment by jw** [comment]
I agree, this is related to issue #234.

**Comment by bitprophet** [comment]
Yea this sounds same as #234, let's roll it into there.
