### ISSUE TITLE
List tasks in modules at site_packages

### ISSUE THREAD

**Issue by ludbek** [pyinvoke/invoke#221]
Is there a way to list every tasks in every modules in site_packages ?

**Comment by bitprophet** [comment]
Interesting question. Big problem is that it's obviously possible to have a `tasks.py` which has nothing to do with Invoke, and conversely, one could distribute Invoke tasks within files named something other than `tasks.py`.

Meaning one would have to do a brute force scanning approach, importing every single module and testing it for presence of a `namespace`/`ns` object or `invoke.tasks.Task` instances. Especially given the danger of import-time code execution, this feels like probably not a great idea.

What is the deeper use case here? People have thrown around ideas like using setuptools entrypoints to 'mark' distributed tasks modules, in the past, to solve the problem of "maybe I installed some third party packages, what tasks did they come with?". For now, explicit importing of such tasks into your local tasks.py is the way to go, but it is early days.

**Comment by ludbek** [comment]
Yup, in fact I am experimenting with discovering and executing tasks in 3rd party modules. What ever I am doing is kind of hackist. But I am curious about its potential. I will let you know how it goes.

Mean while I am curious how `invoke` gets the list of tasks when we do `inv -l`  or `inv -r path/to/tasks -l`. Is there any particular function that api exposes. I tried using `cli.parse(argv)`  but it throws error.

**Comment by jhermann** [comment]
Invoke this! :smirk:

```sh
$ python -c "import tasks; from invoke.tasks import Task; print ' '.join([v.name for k, v in vars(tasks).items() if isinstance(v, Task)])"
check help ci release-prep clean test dist build
```

**Comment by jhermann** [comment]
Also this…

```sh
$ yolk -a | cut -f1 -d' ' | xargs -i+ bash -c 'yolk -d + | egrep -i " invoke[^a-z]" >/dev/null && echo +'
rituals
$ yolk -d invocations
invocations 0.6.2
```

Not fool-proof though as you can see, yolk3k still seems to have problems with the djungle of metadata formats out there.

**Comment by bitprophet** [comment]
The programmatic interface to tasks is largely the Collection class; for the "simple" case of "I have a module with `@task`-decorated functions in them, and no explicit Collection/namespace", the CLI module builds one for you using http://docs.pyinvoke.org/en/0.10.0/api/collection.html#invoke.collection.Collection.from_module (which you could certainly use yourself).

**Comment by ludbek** [comment]
thanx that helps

**Comment by ludbek** [comment]
I am closing this issue as this feature is for other packages to implement.

**Comment by ludbek** [comment]
@bitprophet please visit this [repo](https://github.com/ludbek/easypy). it uses `invoke` at its core. it is totally experimental. comments and feedback are welcome :). once it gets enough feedback work for stable version will begin.
