### ISSUE TITLE
is there a way to change current working directory from within task

### ISSUE THREAD

**Issue by ludbek** [pyinvoke/invoke#225]
I am creating a task which activates a virtualenv and changes user's working directory to her project directory. The task is invoked something like this:

`$ py workon aproject`

@tasks it does
```python
run("source {}/bin/activate".format(project_env_path), pty = True)
## take user to project directory
run("cd {}".format(project_path), pty = True)
```

But the code does not seem to effect user's terminal. How to make it work?

**Comment by sophacles** [comment]
Each call to run starts a new shell, so thats something to keep in mind. A couple specific things regarding the above:

* you can use the virtualenv python specifically by:
```
run('$VIRTUAL_ENV/bin/python script.py')
```
* you can switch directories for a command by:
```
run('cd /new/path && command')
```
* If you'll be doing a lot of work in a specific directory, you can change `invoke`'s working directory by:
```
...
import os
old_pwd = os.getcwd()
os.chdir("/new/path")
run("cmd1")
run("cmd2")
# go back to the starting point
os.chdir(old_pdw)
```

Another tip, for robust scripting is to set variables to full path names when possible like so:
```
env_python = "/path/to/virtualenv/bin/python"
some_other_path = "/path/to/some/resource"

@task
def foo():
    cmd = "{env_python} --opt-resource {some_other_path} foo.py"
    cmd.format(**vars())
    run(cmd)
```

Finally, i like context managers in python so something I do regularly is setup a chdir context manager like so:
```
from __future__ import with_statement  # only for python 2.5
import contextlib
import os

@contextlib.contextmanager
def chdir(dirname=None):
  curdir = os.getcwd()
  try:
    if dirname is not None:
      os.chdir(dirname)
    yield
  finally:
    os.chdir(curdir)

@task
def foo():
    with chdir("/path/to/new/workingdir"):
        run("cmd x.txt")
        run("cmd2 y.txt")
```
Which is equivalent to:
```
path_root = "/path/to/new/workingdir"

@task
def foo():
    cmd1 = "cmd {}/x.txt".format(path_root)
    run(cmd1)
    cmd2 = "cmd2 {}/y.txt".format(path_root)
    run(cmd2)
```

HTH

**Comment by gotgenes** [comment]
Won't using `os.chdir` change where all invoke tasks are currently being run? If so, this means only one invoke task may be run safely at a time, ruling out concurrent tasks, which seems like a shame.

I would hope that the [`Context`](http://docs.pyinvoke.org/en/latest/api/context.html#invoke.context.Context) object could be used to create isolated execution environments where things like the current working directory could be changed without impacting other tasks.

**Comment by sophacles** [comment]
Depends on how multiple tasks are being run concurrently, but it could do that, yes.

In the longer term, Context could be set to do that, via setting cwd argument in in the run function of vendorized pexpect.

**Comment by sophacles** [comment]
I'm going to open a ticket on that specific thing. Good thinking @gotgenes
