### ISSUE TITLE
Add a "run_dir" or similar argument to "run" and "Context.run"

### ISSUE THREAD

**Issue by sophacles** [pyinvoke/invoke#230]
As pointed out by @gotgenes in #225, parallelized task execution could have some issues with runtime cwd. A simple way of handling this, and making some things nice for users in general, is to allow either the `run` function, or the `Context` object (or some combination) to set the `cwd` for each task.

The vendorized `pexpect` used by invoke does have a `cwd` kwarg, that will set the child process' working dir before execution, so this change is relatively straight forward to implement.

**Comment by gotgenes** [comment]
To make concurrency/parallelization possible for tasks, context instances should be self-contained, and tasks should be able to run inside explicit instances of contexts. That is, altering the state of one context object should have no impact on any separate instances. This includes, then, but is not limited to, things like the current working directory.

A similar project, plumbum, suffers from an architecture where running tasks/commands concurrently was not considered; only a single, global context exists for local commands (see tomerfiliba/plumbum#169). invoke has the opportunity to choose a concurrency/parallel-friendly architecture by thinking about independent execution contexts from the start.

**Comment by bitprophet** [comment]
Yea, having a copy of a context for each task is already a thing that should be happening; it's certainly a primary design goal as the point was to escape from the horrible issues around Fabric 1's global state.

FTR we're moving away from pexpect right now in another ticket, but having a similar "look at context/config for desired current cwd/cwd-chain & act on that" behavior is definitely in the cards.

**Comment by gotgenes** [comment]
@bitprophet Excellent; thank you!

**Comment by frol** [comment]
Reading comments to this issue, an interesting idea came to my mind. You are talking about "context instances should be self-contained", "having a copy of a context for each task is already a thing that should be happening" and this sounds like a perfect place to apply Immutable Datastructures! I knew about ImmutableJS, so I googled for something similar for Python. The best fitting project (maintained and feature-rich) is Pyrsistent: http://pyrsistent.readthedocs.org/en/latest/intro.html 

(Just for the reference, I also came across other Python projects implemented Immutable Datastructures, but, unfortunatelly, they are all abondoned: funktown, pysistence, fn.py)

**Comment by elsmorian** [comment]
Just a bump that I have hit this need too - would be really handy to have something like Fabrics lcd ( http://docs.fabfile.org/en/1.11/api/core/context_managers.html ) And the current lack of it has meant I'm now using Fabric for an entirely local task set!

**Comment by darioblanco** [comment]
This is definitely a very common use case and I would love to have the feature as well. If you need some development power, any updated idea about how to proceed with this issue? Would love to help

**Comment by Aiky30** [comment]
I've just started looking at porting a project with the idea of moving all past and future local dev task running instances over to Invoke. I have used the Fabric lcd command in all of my projects and adding an ugly run(cd /some/dir && myconsoletask) is not cool when you need to run multiple commands and as pointed out, changing the current working directory is dangerous for other tasks being executed.

I would happily contribute to this to get it available earlier than a 1.0 release that still looks some way off!!!!!

**Comment by bitprophet** [comment]
I think this is done now, courtesy of #446 which just merged. tl;dr each Context instance is now capable of doing implicit, in-command `cd xxx && real-command-here` prefixing, based on state stored within the Context itself (as opposed to e.g. relying on `os.cwd`). ![](http://i.somethingawful.com/forumsystem/emoticons/emot-toot.gif)
