### ISSUE TITLE
Trouble loading the project-level configuration file

### ISSUE THREAD

**Issue by brutus** [pyinvoke/invoke#234]
I'm using Invoke 0.10.1 in an virtual environment. I have an `invoke.yaml` file next to my `tasks.py` file, but it is ignored. Values from `~/.invoke.yaml` are loaded though. If i use `-f` it works too.

The `tasks.py` imports some tasks from other modules, but the root namespace is created and configured in the `tasks.py` file. I tried using a package for the tasks instead but to no avail.

Any hints?

And btw: if I use a package, do the `invoke.yaml` file needs to be in the package (next to `__init__.py`) or in the parent folder (tried both, none worked)?

**Comment by jw** [comment]
Weird.  Works for me.  Can you add your `invoke.yaml` and `.invoke.yaml` files to the issue?
And the `invoke.yaml` needs to be in the same folder as your `tasks.py` file.

**Comment by brutus** [comment]
If put the `task.py` and `invoke.yaml` files [here](https://gist.github.com/brutus/81b251c02cf2ae7c6ceb) as a gist. Both are in the same directory at the top level of the project.

I currently use no `~/.invoke.yaml` file, but when I create one for testing purposes it works. It also works if I use the `-f` parameter: `inv -f invoke.yaml sometask` woks, `inv sometask` not.

**Comment by jw** [comment]
Thanks @brutus, but there seem to be some issues with your gist.  The task.py should be tasks.py, the corelib module is unkown, not is the setup, clean, css_ns,... tasks.  I've created another [gist] (https://gist.github.com/jw/8d0b37adf54609f317ce) for you. Could you please give it a try?

**Comment by brutus** [comment]
Thank you: your example works in any case, I came up with. And sorry, the missing *s* in my gist's `tasks.py` was a typo and *corelib* is some project local stuff. 

But I assure you, the example gist **works for me — but only if I include the *invoke.yaml* trough the `-f` option**, else the data is not loaded, even both files are in the same directory and named correctly. If I store the data in the namespace configuration instead, it works too.

What seems to be the problem is, that **I'm using a namespace** in my `tasks.py`: When I don't create a namespace — like in your example — the data from `invoke.yaml` is loaded. When I create a namespace it's not. It doesn't matter if I configure it, as soon as the namespace is created, the data is not loaded.

**Comment by jw** [comment]
You're right, when using a `ns = Collection()` at the bottom on my gist, the project yaml is not read.  You can see that when running invoke with the `-d` option.  This is a bug related to #210.

**Comment by bitprophet** [comment]
Wacky times, thanks a lot for reporting and kicking this around! I will try to reproduce this on my end soon, I don't personally use project-level conf files yet (though I do use explicit namespaces everywhere) so I haven't had a chance for it to bite me. But it sounds totally plausible and hopefully there's a simple, silly answer.

**Comment by gtback** [comment]
I've been digging around and think I solved this one. PR coming shortly.

**Comment by gtback** [comment]
@brutus: Can you see if the change I made in 34e6a7a668a7db97170ceca5458e22041a66cdcc solves the problem for you, in case @bitprophet doesn't have a chance to reproduce this bug?

**Comment by brutus** [comment]
@gtback: Just did a quick check and it worked. Thx! Will fiddle some more and get back to you if anything bails.

**Comment by bitprophet** [comment]
Thanks to all 3 of you for poking at this ![](http://i.somethingawful.com/forumsystem/emoticons/emot-toot.gif)
