### ISSUE TITLE
Support .yml extension

### ISSUE THREAD

**Issue by philtay** [pyinvoke/invoke#249]
Even if the recommended extension for a YAML file is `.yaml`, it would be nice to have support for `.yml` as well. Currently only `invoke.yaml` is recognized as a configuration file; `invoke.yml` is ignored. It's a bit ugly to have something like `.travis.yml` next to `invoke.yaml`. I'd prefer to be consistent and use only one extension for YAML.

**Comment by matleh** [comment]
this is a duplicate of #232

**Comment by bitprophet** [comment]
Thanks @matleh!
