### ISSUE TITLE
Align Tox and Travis builds

### ISSUE THREAD

**Issue by gtback** [pyinvoke/invoke#252]
Just a suggestion: 

To minimize differences between local testing and CI testing on Travis, configure most of the testing steps in Tox, and then tell Travis to just run tox. I'm not sure how well the integration tests could be moved over, but building docs, flake8, coverage, etc. are all good candidates. 

On the other hand, some amount of variability in testing environments is a good thing, but neither `spec` nor `tox` cause the tasks.py module at the root of the repo to get loaded, which has been causing a lot of the recent Travis builds to fail. 

The process is explained pretty well in [this blog post](http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/) (minus the Django stuff). I've done something similar on a different project: [tox.ini](https://github.com/CybOXProject/python-cybox/blob/master/tox.ini), [.travis.yml](https://github.com/CybOXProject/python-cybox/blob/master/.travis.yml). 

I'm not sure if something similar would work for Appveyor. I don't have any real experience with that.

I'm happy to help do this if it sounds beneficial.

**Comment by bitprophet** [comment]
See https://github.com/fabric/fabric/pull/1314 for my current opinion on tox :) as stated there, I may come around eventually but for now we have enough integration-y things and the like that I'm dragging my feet.
