### ISSUE TITLE
Colored output in invoke

### ISSUE THREAD

**Issue by kracekumar** [pyinvoke/invoke#256]
```python
#tasks.py
# -*- coding: utf-8 -*-

from invoke import run, task


@task
def test():
    """Run all tests.
    """
    run("py.test -s -v")
```

### Output
![screen shot 2015-06-25 at 5 23 36 pm](https://cloud.githubusercontent.com/assets/311929/8353756/f9dde3ca-1b5e-11e5-8ce1-c747f9e9d96a.png)

Using `py.test -s -v` colored output is retained where as `invoke test` output doesn't. Do I need to install third party plugin or pass a flag ?

**Comment by bitprophet** [comment]
Chances are py.test is trying to automatically hide colors when it thinks it's being run outside of a terminal. Try adding `pty=True` (so `run("py.test -s -v", pty=True)`).

I thought there was an FAQ for this, but I don't see one, so I will add one. (@kracekumar - Did you look at the FAQs before posting this, by the way? If not, why not? The docs tree is still young, wondering if we can make things more visible.)

**Comment by kracekumar** [comment]
@bitprophet Thanks. Adding `pty=True` fixed it. 

I didn't read FAQ, but searched for `color` in the docs and found one reference which was for something else.

If it is ok I can send a PR updating `FAQ`.

**Comment by bitprophet** [comment]
Don't worry about it, I'm already almost done :) thanks tho!

**Comment by kracekumar** [comment]
Awesome :+1:

**Comment by bitprophet** [comment]
https://github.com/pyinvoke/invoke/commit/3b9ade5d7af8bf093c0f91f2b59a3d7fe904d7cb

**Comment by pylang** [comment]
I'm having the same issue on Windows.  It's saying the `pty` module doesn't work.

**Comment by ShaiAvr** [comment]
Having the same issue on Windows 11. `pty` isn't supported so it's not a solution for colored output.

**Comment by maxsegl** [comment]
Is there any solution for windows? Would love that feature.
