### ISSUE TITLE
Add a list type parameter / nargs support

### ISSUE THREAD

**Issue by epicserve** [pyinvoke/invoke#264]
So I looked in the docs and I'm not finding how to add a list type parameter. For example if have a task like `test` and I want to add a list parameter called apps, right now this wouldn't work.

If my invoke file is like this:

```python
from invoke import task

@task
def test(apps=[]):
    print(apps)
```

and I run it with:

```
invoke test apps=app.foo app.bar
```

I get the following returned:

```
No idea what 'app.bar' is!
```

**Comment by epicserve** [comment]
The work around I came up with is this:

```python
import django
from invoke import task
from django.core import management

@task
def test(verbosity=0, test_label=''):
    django.setup()
    if test_label:
        test_label = test_label.split(' ')
        management.call_command('test', *test_label, verbosity=verbosity)
    else:
        management.call_command('test', verbosity=verbosity)
```

Which then allows you to call the task like this:

```
invoke test -v 2 -l 'tests.TestViews.test_index tests.TestViews.test_extra'
```

**Comment by bitprophet** [comment]
See #132, this isn't implemented yet, but we'd like to add it if we can find a way that isn't too hacky. thanks!
