### ISSUE TITLE
`ns` name is mandatory for the root namespace Collection

### ISSUE THREAD

**Issue by frol** [pyinvoke/invoke#268]
Invoke forces to use `ns` variable name, but I could never find anything about this in the documentation. Shouldn't it be documented?

**Comment by frol** [comment]
Reading the source code, I have discovered that I can use `namespace` variable name which is at least less cryptic.
https://github.com/pyinvoke/invoke/blob/master/invoke/collection.py#L160

**Comment by bitprophet** [comment]
It's documented here, http://docs.pyinvoke.org/en/0.10.1/concepts/namespaces.html#starting-out - landing page -> click "Constructing namespaces" -> pretty close to top of doc :)

Not sure if you didn't look hard enough or if there's an obvious improvement we could make to our doc structure, please let me know!

**Comment by frol** [comment]
Indeed! I'm sorry for that. It seems that I have overlooked that notice. Now, as I'm reading it again I see that it was also mentioned in the Getting Started guide. Probably, I missed it because of that examples seemed too easy to read descriptions to the end of the paragraphs. My suggestion would be to add a comment about `ns` and `namespace` names right into the code examples.

**Comment by bitprophet** [comment]
That sounds reasonable. See 6aeffbde925291c281c700be0f1fac7c50a6fbc4 - thanks!

**Comment by frol** [comment]
Great! Thank you!
