### ISSUE TITLE
`run` on Windows ignores a part of a command that is after a new line (\n)

### ISSUE THREAD

**Issue by frol** [pyinvoke/invoke#271]
I digged into the problem and discovered that the issue seems to be a Windows cmd, which is run from `run` by `subprocess.Popen(shell=True)`.

Here is the reproduction:

```
python -c 'import subprocess; subprocess.Popen("echo 1 \n echo 2", shell=True)'
```

Output on Windows:

```
1
```

Output on Linux/OS X:

```
1
2
```

Even when I wrap the command with `/bin/bash -c` it is too late since cmd trucate the command before it get passed into `bash`.

The way to make it work is to drop `shell=True` and explicitly wrap the command with `bash`:

```
python -c 'import subprocess; subprocess.Popen(["bash", "-c", "echo 1 \n echo 2"])'
```

I have no idea how it should be addressed in Invoke since not everybody have bash on Windows... At the very least we can add a warning if there is a `\n` in a command running on Windows.

**Comment by frol** [comment]
I've been trying to overload a runner, but I cannot find a place where I can update a Config with my runner implementation. I've found only one place where it tries to read the `runner` value and fallbacks to `Local`: https://github.com/pyinvoke/invoke/blob/master/invoke/context.py#L52

How can I set `runner` to a global Config? Is monkey-patching is the only way?

**Comment by frol** [comment]
My workaround is to force Popen to use bash everywhere (it works fine for me on Window, Linux, OS X):

```python
import subprocess

from invoke import Collection, runners


class LocalBashRunner(runners.Local):
    """
    Execute a command on the local system in a subprocess with bash on all OSes.

    This patch is added due to a bug on Windows:
    https://github.com/pyinvoke/invoke/issues/271
    """

    def start(self, command):
        """
        Initiate execution of ``command``.
        """
        if self.using_pty:
            super(LocalBash, self).start(command)
        else:
            self.process = subprocess.Popen(
                ['bash', '-c', command],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

namespace = Collection(
# ...
)

namespace.configure({
    'runner': LocalBashRunner,
})
```

**Comment by bitprophet** [comment]
Hm, what is subprocess using by default for the shell on Windows, is it still finding a `sh`, and is that actually different from `bash`? (I assume you're using Cygwin or something? Otherwise not sure how Windows can even have a `/bin/bash`!)

Also glad to see that the `runner` configuration stuff is working as intended. Any suggestions for making that smoother (or easier to discover that it's possible)?

Also, note-to-self-sorta, see #67 which is about making the shell more selectable.

**Comment by frol** [comment]
@bitprophet It uses `cmd.exe` on Windows! I've just run an experiment from Cygwin:

```
$ python -c 'from subprocess import Popen, PIPE; Popen("echo %cmdextversion%", shell=True)'
2
```
