### ISSUE TITLE
arguments with underscores are not recognized on the command line

### ISSUE THREAD

**Issue by chumpalump** [pyinvoke/invoke#286]
```python
from invoke import ctask as task

@task
def foo(ctx, bar):
    print("foo: ", bar)

@task
def foo2(ctx, bar_me):
    print("foo2: ", bar_me)
```
The no-underscore version of foo works fine.
```
$ invoke foo --bar=spam
foo:  spam
```
Add an underscore, and the argument is not recognized.
```
$ invoke foo2 --bar_me=spam
No idea what 'spam' is!
```

**Comment by bitprophet** [comment]
This is intended behavior, please see http://docs.pyinvoke.org/en/0.11.1/concepts/cli/intro.html#dashes-vs-underscores-in-flag-names :) thanks!
