### ISSUE TITLE
Hiding tasks from --list?

### ISSUE THREAD

**Issue by fgimian** [pyinvoke/invoke#290]
Hello, hope everything is going well :smile: 

Is it possible to hide tasks from the `--list`?  If not, is there a way to access config (via ctix) in a regular function?

Thanks so much for your help and invoke :smile: 
Fotis

**Comment by bitprophet** [comment]
Is there a reason you can't simply do something like this?

``` python
def private_non_task_function(context):
    context.whatever()

@ctask
def user_facing_task(context):
    private_non_task_function(context)
```

Otherwise, I don't quite get what you're trying to do :)

**Comment by fgimian** [comment]
Sweet, yep, that'll do the trick.  Thanks!
