### ISSUE TITLE
Tests are failing on appveyor

### ISSUE THREAD

**Issue by pfmoore** [pyinvoke/invoke#305]
The test suite is currently failing on Windows. The appveyor builds are showing as red. I have a patch which I will submit once the CI has run on my clone. Note that the patch will still fail on the main repo, this is because of #302 but when #304 is applied, the appveyor tests all pass.

@bitprophet if you get CI test failures on Windows and need help with fixes, please feel free to ping me. If the only thing stopping us having a clean Windows build is lack of resource with Windows knowledge, I'm happy to help out.

**Comment by pfmoore** [comment]
OK, #306 created. In conjunction with #304, tests should start passing on Windows again.

**Comment by bitprophet** [comment]
Previously, tests on appveyor would fail after ~9-12 minutes; the build including #306 (https://ci.appveyor.com/project/bitprophet/invoke/build/1.0.208/job/0u2iid1i4um7w60g) is now up to 20+ minutes...but...it *seems* to be stuck on a single test, whichever one it's running first under `Program.core_args` (which is especially vexing as that stuff should all be basic, non platform specific unit tests).

Hoping it's just really crummy output buffering or something; guess we'll see, depending on whether appveyor has a timeout.

**Comment by bitprophet** [comment]
Yup it hit that timeout. Rest of jobs in that build are still queued so we'll see if it's a fluke or what. Gonna put aside and go back to other things for now.

**Comment by pfmoore** [comment]
I wonder if appveyor is running the jobs without a console somehow, and that's affecting the msvcrt stuff. I'll try to see if I can work out what's going on.

**Comment by pfmoore** [comment]
OK, worked it out - see #316

**Comment by bitprophet** [comment]
Sweet, thanks for poking at that. Just merged, we'll see if my recent merges broke anything else I guess. In a while. Poor slow appveyor =/ I will check back here before I cut 0.12.1. (Soon, now that I finally finished #308, sigh).

**Comment by bitprophet** [comment]
Canceled the intermediate jobs since they also wouldn't pass; the job after I merged #316 seems to have passed, at least on the first interpreter matrix cell: https://ci.appveyor.com/project/bitprophet/invoke/build/1.0.213/job/8k308muc61bed5jt

We don't/can't run the integration tests so I can't tell if my "nested invoke" bugfix works on Windows, but as long as the more normal test cases work fine, that's plenty good enough for me...

**Comment by bitprophet** [comment]
Yup all passed.
