### ISSUE TITLE
@task seems to eat docstring

### ISSUE THREAD

**Issue by thebjorn** [pyinvoke/invoke#313]
I'm trying to document my task library using Sphinx, and ran into a problem with docstrings and autodoc.  How to reproduce (before/after functions added to verify that sphinx works):

```
(sphinxtst) go|c:\srv\tmp\ctaskdocs> cat tasklib.py
from invoke import task, ctask, run

def before():
    "before docstring"
    pass

@ctask
def hello_ctask(ctx):
    "hello ctask"
    ctx.run('echo world')

@task
def hello_task():
    "hello task"
    run('echo world')

def after():
    "after docstring"
    pass
```

A minimal conf.py

```
(sphinxtst) go|c:\srv\tmp\ctaskdocs> cat docs\conf.py
# -*- coding: utf-8 -*-
import sys, os
extensions = ['sphinx.ext.autodoc']
```

and a minimal root document using autodoc

```
(sphinxtst) go|c:\srv\tmp\ctaskdocs> cat docs\contents.rst

tasklib
-------

.. automodule:: tasklib
   :members:
   :undoc-members:
```

Set the pythonpath to directory containing tasklib.py to keep sphinx happy

```
(sphinxtst) go|c:\srv\tmp\ctaskdocs> set PYTHONPATH=%CD%

(sphinxtst) go|c:\srv\tmp\ctaskdocs> sphinx-build docs build
```

The resulting build/contents.html only contain references to the functions that do not have the `@task/@ctask` decorators.

**Comment by thebjorn** [comment]
Well.. after some meditation, a bit of food, and re-reading the sphinx docs, I've come up with an incantation that works:

```
tasklib
-------

.. automodule:: tasklib
   :members:

.. autoclass:: tasklib.hello_ctask
.. autoclass:: tasklib.hello_task
```

ie. remove `:undoc-members:` on automodule, and add an autoclass directive for every function that has a `@task/@ctask` decorator.  Neither `:members:` not `:undoc-members:` should be specified on autoclass (or you'll get all of the Task class' innards).

The various warnings about `"no attribute '__bases__'"` and duplicate object description (between the Task class and the Task instance) should all be benign.

**Comment by thebjorn** [comment]
The ``autoclass`` approach turned out to be sub-optimal since it just included the task's docstring, and not the task's parameter list (or parameter help).  Maybe a solution would be to inject the parameter list into the task's docstring, but that seems very hackish.

Instead, I decided to write a small sphinx extension (https://github.com/datakortet/dk-tasklib/blob/master/docs/ext/autotaskdoc.py) that looks for a Collection inside a module and lists all tasks it finds with name, docstring, and a table of parameter values and help strings (from `ParserContext.help_tuples()`).

**Comment by thebjorn** [comment]
fwiw, a sample of the shpinx extension: http://pythonhosted.org/dk-tasklib/dktasklib.html#module-dktasklib.docs (pretty bare-bones, but works for my limited use-cases).

**Comment by bitprophet** [comment]
I went a slightly different route to solve this, one that doesn't require the extra `.. autotaskdoc::` directives but adds a new 'Documenter' to register with autodoc - see #520 (or http://invocations.readthedocs.io/en/latest/api/autodoc.html).

It could do a LOT more than it does - it's crying out for a custom domain that can display details about tasks, collections etc - but that can be iterated on later I think. Gonna close this for now as "solved both by requester on their end and now also generally". Thanks!!
