### ISSUE TITLE
tasks without args fail in merge_dicts()

### ISSUE THREAD

**Issue by jenisys** [pyinvoke/invoke#317]
**INVOKE VERSION:** invoke-0.12.0, repository HEAD (same) and invoke-0.11.1
**SYNDROME IN:** 
* tasks without args or 
* ``ctask`` without additional args besides ``ctx``.

When I run invoke with a rather simple ``tasks.py`` file:
```python
from invoke import task, run

@task
def clean():
    pass
```
the following error occurs:

```shell
(.venv_py27) $ invoke clean
Traceback (most recent call last):
  File "/.../.venv_py27/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/program.py", line 270, in run
    self.execute()
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/program.py", line 378, in execute
    executor = self.executor_class(self.collection, self.config, self.core)
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/program.py", line 246, in config
    env_prefix=self.env_prefix,
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/config.py", line 357, in __init__
    self.merge()
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/config.py", line 518, in merge
    self._merge_file('project', "Per-project")
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/config.py", line 537, in _merge_file
    merge_dicts(self.config, data)
  File "/.../.venv_py27/lib/python2.7/site-packages/invoke/config.py", line 588, in merge_dicts
    for key, value in updates.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by jenisys** [comment]
QUICKFIX: Protect against recursive-call with ``None``.

```python
# -- FILE:invoke/config.py:588
if updates is None:
    return
# -- CURRENT IMPLEMENTATION: Starts here
...
```

**Comment by jenisys** [comment]
NOTE:
* With invoke-0.12.2 the behaviour is worse. Now it fails even with tasks that have args.
* After the patch from above is applied, everything is fine again.

**Comment by rlucioni** [comment]
@jenisys any chance you've got an empty configuration file (e.g., `invoke.yaml`) lying around? I'm only able to reproduce this with an empty configuration file. The exception goes away when I remove that file or fill it in.

**Comment by jenisys** [comment]
OOPS, correct. I just touched it to use it for further explorations.
After I remove it everything is OK (with invoke-0.12.2).

The weird think: After I create an empty file "invoke.yml" again, the problem does no longer appear.
Still, the issue is resolved for me (I can no longer reproduce the problem with the latest version). I close the issue.

**Comment by rlucioni** [comment]
@jenisys you're unable to reproduce the issue because your configuration file ends in `.yml`. Invoke is looking for configuration files ending in `.yaml`, `.json` or `.py`. See the [Loading](http://docs.pyinvoke.org/en/0.12.2/concepts/configuration.html#loading) section in the docs for more.

If you switch back to using an empty `.yaml` file, your sample task above should fail. Similarly, if you switch to using an empty JSON file, a `JSONDecodeError` is raised. This one makes sense, since the empty JSON file isn't valid JSON. Adding an empty object to the file (`{}`) resolves the issue. Empty Python files cause no problems.

**Comment by jenisys** [comment]
Mmh, sorry. I actually had an "invoke.yam". 
But when I use it everything is OK (even after removing and readding it) and executing a task with invoke. 
The JSON fails as expected (and described above), because an empty JSON file is not valid.
