### ISSUE TITLE
Getting print error with Python 3

### ISSUE THREAD

**Issue by khchine5** [pyinvoke/invoke#325]
Hi ,
I have started using Invoke as a replacement of Fabric,hoping to get Python 3 works. I have done almost all code changes to adapt my code the new Invoke syntax and my new code works fine with Python 2 but I am still get encoding error with almost all print statements either on my code or on invoke's code.
My config:
-Invoke 0.12.2
-My code use future (==0.15.2)packages as porting tool to Python 3.
-Python version : 3.4.3
With 'inv' command , I got the following:

```
(py3) khchine5@khchine5-300E5EV-300E4EV-270E5EV-270E4EV:~/PycharmProjects/atelier$ inv -l
Traceback (most recent call last):
  File "/home/khchine5/.virtualenvs/py3/bin/inv", line 11, in <module>
    sys.exit(program.run())
  File "/home/khchine5/.virtualenvs/py3/lib/python3.4/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/home/khchine5/.virtualenvs/py3/lib/python3.4/site-packages/invoke/program.py", line 351, in _parse
    self.list_tasks()
  File "/home/khchine5/.virtualenvs/py3/lib/python3.4/site-packages/invoke/program.py", line 552, in list_tasks
    print("Available tasks:\n")
  File "/home/khchine5/.virtualenvs/py3/lib/python3.4/codecs.py", line 374, in write
    self.stream.write(data)
TypeError: must be str, not bytes
```

Although , when I run an other invoke command which use print statement , it works file , like :

```
(py3) khchine5@khchine5-300E5EV-300E4EV-270E5EV-270E4EV:~/PycharmProjects/atelier$ inv --version
Invoke 0.12.2
```
Could this be a confit between future package used by my code when I call invoke and six used my invoke packages ?

Thanks.

**Comment by bitprophet** [comment]
Honestly not sure if your diagnosis is correct, but I don't have any better ideas, this is new to me. I am not very familiar with `future` either.

We have encoding issues reasonably often but they're always in spots where we explicitly call `.encode` or `.decode` on string/byte objects, or do low level stream things. As you noted, your error comes from just a `print()` with a string literal in it.

So yea, I would start by investigating if something in your own code is somehow triggering this. I.e. if you remove your code from the picture and just run a minimal `tasks.py` with a single tiny do-nothing task in it, does this still happen? If not, start adding back your code until it breaks, that sort of thing.

**Comment by khchine5** [comment]
Thanks @bitprophet .
You are right. Actually, I have used the following code to support new python3 encoding but as we can the new python3 version has changes how to handle this.
```
# thanks to http://stackoverflow.com/questions/11741574/how-to-print-utf-8-encoded-text-to-the-console-in-python-3
# import sys, codecs, locale
# sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout) 
```
I close this issue as it is not related to Invoke.
