### ISSUE TITLE
CTRL+C/Sigkill stopped working

### ISSUE THREAD

**Issue by noirbizarre** [pyinvoke/invoke#327]
Sigkill/CTRL+C does not kill the process any more in 0.12.2.

I can reproduce this with any long running process waiting for a sigkill to end.
I think this is the same issue as #315 and that it's not Docker related.

**Comment by svetlyak40wt** [comment]
I've checked, and Ctrl+C works perfectly in invoke==0.11.1.

**Comment by svetlyak40wt** [comment]
Sorry, I've rechecked, how 0.11.1 works. It exists on Ctrl-C, but child process remains alive.

I've downgraded to the 0.10.1 and now seems everything works fine there.

**Comment by noirbizarre** [comment]
Yep, it worked fine in 0.10.1

**Comment by bitprophet** [comment]
This seems like a duplicate of #315.

**Comment by svetlyak40wt** [comment]
Seems, neither this nor #315 issues are solved but both are closed. Why?

**Comment by bitprophet** [comment]
See #152, this is out in 0.13.

**Comment by svetlyak40wt** [comment]
Ok, thank you!
