### ISSUE TITLE
Task-list format option

### ISSUE THREAD

**Issue by bitprophet** [pyinvoke/invoke#33]
I.e. instead of just `inv --list` spitting out the current default flat list, allow things like `inv --list nested` for a nested/indented display, `inv --list=foo` to just list the tasks within namespace `foo`, etc ad infinitum.

LATER EDITS: so a lot of strongly related tickets have popped up and there seem to be two major currents:

- Formatting, i.e. flat with dots vs nested vs machine-readable
- Content, i.e. all tasks vs just namespaces vs just tasks within a given namespace

Seems unwise/impossible to shoehorn all of that under a single optional value to `--list` so I'm sure we'll grow some additional flags either way, with the main question being which (if any) such option deserves to live as the optional `--list`value.

Brainstorm:
- Format could be a single flag with string option, e.g. `--list-format (flat|nested|machine)` (what term do other tools use for "machine-readable" anyways? Can't remember offhand...LATER EDIT: actually these days we often just use JSON for that and just call it eg `--list-format=json`) or it could be a handful of booleans like `--list-nested`, `--list-machine`.
  - Former feels easier to implement, harder to fuck up by giving >1 at a time, and easier for users to grasp (i.e. fewer options to think about) so it seems like a no-brainer.
- Content needs levers for 'root' (though this needs to not clash with the related-but-distinct `--root` flag which changes where tasks files are sought from; but perhaps we should be, well, _namespacing_ those as well so they are renamed to eg `--discovery-root`) and 'depth` and I think that's it, since those together can enable just about anything:
  - "Show me everything": root is the top of the namespace, depth is None
  - "Show me just the namespaces": root is top of namespace, depth is 1
  - "Show me just tasks under namespace foo"
- Might actually need another lever for the confluence of those two, i.e. "I am listing some subset of tasks and I want to tweak whether they are shown as full paths or sub-paths"?
  - Though at *this* point I wonder if users who want a non-full-path display (i.e. `inv --namespace foo --list` spitting out task names like `bar` and `baz` instead of `foo.bar` and `foo.baz`) should be relying on "each Python module can be its own standalone namespace" and doing things like `inv --collection=namespace --list"` instead (see [Collection loading](http://docs.pyinvoke.org/en/latest/concepts/loading.html#configuring-the-loading-process).)
    - Since, if one truly wants to 'focus' on a given sub-namespace, giving it to `--collection` automatically ensures that *everything* - display, invocation, etc - instantly works as you'd expect.
  - The main argument I can think of why one would _not_ want to go that route is if one wanted to do nontrivial slice n dice of namespace contents within the root tasks file (such that the namespace does not reflect Python module or package structure.)
  - However it's not necessarily out of the running, we could either implement things to be depth-aware and default to stripping out parent levels on display/invocation – or (probably better) just make it possible to say "hey I know you loaded my root tasks namespace, but I'd like you to act as if I gave you `foo.bar` as an argument to `--collection` - even though, between you and me, `foo.bar` isn't visible on the Python import paths."
  - Rereading this later, my gut says "ugh we're making this too complex, just add another flag if people REALLY want to see non-full paths for some stupid reason". And besides, what happened to the 'nested' idea? That's another way to show the 'short' names while clearly presenting depth/parentage.
- Minor quirk: do we bother showing the root namespace when we are being asked to "show me the namespaces"? I'm leaning towards no, but might be nice to be explicit...? e.g. "your namespaces are: `(root)`, `foo` and `bar`"

**Comment by bitprophet** [comment]
See also #104 which doesn't entirely obviate this but does intend to implement one major other "list format" (machine-readable).

**Comment by bitprophet** [comment]
#380 is another "folks definitely want this" example.

When I originally wrote this ticket, optional flag args weren't implemented, but #57 got done some time ago, so nothing is in the way of this besides the actual implementation of additional list formats.

**Comment by bitprophet** [comment]
See also #379 which is a strongly related request for "list just the namespaces", "show namespace docstrings when listing (vs task docstrings when doing --help)" and so on.

**Comment by bitprophet** [comment]
Starting out with the obvious approach, e.g:

- `--list` backwards compat
- `--list foobar` lists only tasks within `foobar`
- `--list-depth N` limits depth, e.g. `--list --list-depth 1` shows just top level tasks/namespaces
- `--list-format nested` shows nested tree, `--list-format json` outputs JSON, etc

Still not sure how to handle namespace stripping (eg. `--list foobar` - is the output in normal mode `foobar.task1`, `foobar.task2` or simply `task1`, `task2`?) but I think I'll _start_ with the easy & clean option, which is no stripping. (Plus, as noted in the desc, `--list-format nested` will probably strip incidentally.)

This stuff should end up more refactored and flexible just by virtue of implementing all the rest, so adding on a strip option should be relatively painless if enough users clamor for it.

**Comment by bitprophet** [comment]
Also pondering whether use of `--list-depth` and/or `--list-format` should imply `--list`, it'd be a bit less typing and it's not like those flags could mean anything if given on their own otherwise. Smells like another "nice to add" later.

**Comment by bitprophet** [comment]
Also thinking the nested display option _probably_ wants to not bother with the first-line-of-docstring column, since it degrades poorly once nesting gets too deep (e.g. trying to wrap the docstring line into a narrow column would eventually get ridiculous and take up far too much _vertical_ space.) In an ideal world we'd just borrow a page from responsive web UX design and have the docstring column disappear at that point, but I don't have that kind of time right now :(

**Comment by bitprophet** [comment]
Also, the JSON format "wants" to be very rich and contain fully serialized JSON copies of Task and Collection objects. In the interests of expediency (and also because serialization is never actually simple to do right, and also adds more friction re: changing these classes' APIs) I'm sticking to largely the same data that is exposed in the other formats: task and collection names, docstrings, and relationships.

**Comment by bitprophet** [comment]
While I'm conversing with myself: contemplated whether it was worth mentioning these new flags in the getting-started document, but I don't think it is, just confuses things. Seems appropriate for it to remain discoverable via `--help` and the CLI docs (aka "verbose `--help`") for now.

**Comment by thinkwelltwd** [comment]
> ...use of --list-depth and/or --list-format should imply --list

+10! 

> Smells like another "nice to add" later.

My preference would be to start out with the --list implication from the get-go.

>  I think I'll start with the easy & clean option, which is no stripping.

SGTM.

>Seems appropriate for it to remain discoverable via --help and the CLI docs

I think so too. After all, there's likely a statistically significant percentage of invoke users that only have list depth of 1 anyway. More complicated use cases will require a little docs reading.

**Comment by bitprophet** [comment]
Grumble, so by innocently trying out the optional-value form of `--list`, I run into a before unseen limitation with optional flags (one I don't see reported by anyone else yet.)

I implemented optional-value flags in #57 and since then I've personally only really used it for flags that tend to be given by themselves, such as the original case of `--help`. You're not combining `--help` with anything; you're either giving it solo for general help or with an argument for per-task help. No other flags make sense with `--help`.

Now, though, we not only want, but need, the ability to invoke things like `inv --list --list-format=nested`. Which trips the ambiguity checking implemented in #57 (see its comments for some details on that) because we cannot tell if the user was intending the argument-like value `--list-format=nested` as the actual value for `--list`, or not.

----

Clearly, in a _general_ sense, it's impossible to globally "fix" the problem because any string-wanting optional-value argument _could_ want a very argument-like string value, up to and including truly valid-for-this-parser-context arguments.

However, my gut is telling me that _when_ the ambiguous value _is_ an otherwise valid-for-this-parser-context token (so, another flag, or the name of another possible parser context aka task) it might be better to ease off on the ambiguity freaking-out. In such situations, it really seems far more likely the user is trying to do something like I'm trying to do above, than that they're screwing up.

Need to dig a bit to see if I can remember what case I had where that situation still wanted the hardcore refuse-to-guess behavior...worried if I change this it'll tank something else important.

**Comment by bitprophet** [comment]
I guess another "solution" here is for the user to remember to give an optional-value flag at the end of the invocation, but that seems kinda shitty to me. Even if it's tempting to go "good enough, you have a deadline" I can just see a lot of users trying to use the new shiny list functionality and running headlong into this. Esp since intuitively one kinda wants to give `--list` before the other args that modify its behavior.

**Comment by bitprophet** [comment]
Overnight epiphany, this ought to get implemented as something vaguely pluggable so it's easier to add more later or for users to add their own w/o needing a PR.

**Comment by bitprophet** [comment]
Fleshing out the tests more, I realize that the tree view can actually end up being _less_ wide in the name-of-tasks column, versus the flat view - because a constant sized 2 or 4 space indent is almost always _less_ than the name of the outer collections!

E.g. `build.docs.html` has 11 characters before you get to the `html`, whereas 2x4-space indents would only be 8 characters - and that's with some pretty short collection names to boot.

So I think having docstrings in both views is probably actually fine for now...

**Comment by bitprophet** [comment]
Quick brainstorm re: tree output format for posterity (I'm probably just gonna pick whatever looks best to me offhand, for expediency, but as above I could see us switching it again later or whatever.)

My first off the cuff approach was 2 space indents, no dots:

```
  shell          Load a REPL with project state already set up.
  test           Run the test suite with baked-in args.        
  build          Tasks for compiling static code and assets.   
    all*         Build all necessary artifacts.                
    ext          Build our internal C extension.               
    docs         Tasks for managing Sphinx docs.               
      all*       Build all doc formats.                        
      html       Build HTML output only.                       
      pdf        Build PDF output only.                        
    python       PyPI/etc distribution artifacts.              
      all*       Build all Python packages.                    
      sdist      Build classic style tar.gz.                   
      wheel      Build a wheel.                                
  deploy         How to deploy our code and configs.           
    everywhere*  Deploy to all targets.                        
    db           Deploy to our database servers.               
    web          Update and bounce the webservers.             
  provision      System setup code.                            
    db           Stand up one or more DB servers.              
    web          Stand up a Web server.                        
```

After my epiphany number 2 above, I made it 4 space indents since saving horizontal space seemed less necessary:

```
  shell            Load a REPL with project state already set up.
  test             Run the test suite with baked-in args.        
  build            Tasks for compiling static code and assets.   
      all*         Build all necessary artifacts.                
      ext          Build our internal C extension.               
      docs         Tasks for managing Sphinx docs.               
          all*     Build all doc formats.                        
          html     Build HTML output only.                       
          pdf      Build PDF output only.                        
      python       PyPI/etc distribution artifacts.              
          all*     Build all Python packages.                    
          sdist    Build classic style tar.gz.                   
          wheel    Build a wheel.                                
  deploy           How to deploy our code and configs.           
      everywhere*  Deploy to all targets.                        
      db           Deploy to our database servers.               
      web          Update and bounce the webservers.             
  provision        System setup code.                            
      db           Stand up one or more DB servers.              
      web          Stand up a Web server.                        
```

Think that looks a bit nicer, and it doesn't even take up THAT much more room since the deepest nest level tends to 'absorb' extra indents for anything below it.

**Comment by bitprophet** [comment]
My gut is saying the leading dots, while slightly noisier, is more idiot-proof and less ambiguous. The trailing dots look like the asterisks I'm using for 'default task for namespace' and might lead folks to wonder if they signify "some other special kind of task" instead of "a collection".

It's also tempting to rub some ANSI on here too, given it's intended solely for human evaluation (anything not so, would want the upcoming JSON output.) E.g. bold collection names. Not sure.

**Comment by bitprophet** [comment]
Alias display also presents some minor issues, e.g. do they also get leading dots or not? If they do, e.g. `.all* (.everything)` now there's ambiguity re: whether we're trying to hint that they are aliases, or if we're for some reason displaying additional subtasks (i.e. is `build.all.everything` valid?)

For now I'm going with consistency and putting dots everywhere; I suspect aliases aren't used terrifically often anyways and we can easily tweak some of this later. (Again, being human facing and providing a computer-facing alternative means we don't even really have to consider minor changes to this stuff as breaking backwards compat.)

**Comment by bitprophet** [comment]
> -1 It wouldn't seem proper to be valid. Seems more intuitive to my brain that the trailing asterisk indicates running all commands in that namespace / collection.

That's one minor issue with my choice of fixture data - the "default task does all the things" pattern is (IME) common, but is not actually a property of what it means to be a default task for a collection. It's entirely plausible to have a collection of tasks where the default task just does its own thing, runs some non-full subset of the other tasks in the collection, or etc.

So when I was talking about 'all' vs 'everything' and the dots, I just meant that if the default task has an alias, and we display both the primary name and the alias on the same line, both with leading dots - it starts to resemble a nested task path that doesn't really exist. But this is minor I think.

**Comment by bitprophet** [comment]
Cool, nested format base case is implemented, e.g. here's it on Invoke's internal task tree:

```
» inv -l -F nested
Available tasks ('*' denotes collection defaults):

  coverage                 Run pytest in coverage mode. See `invocations.pytest.coverage` for details.
  integration              Run the integration test suite. May be slow!
  sites                    Build both doc sites w/ maxed nitpicking.
  test                     Run pytest. See `invocations.pytest.test` for details.
  vendorize                Vendorize Python package ``distribution`` at version/SHA ``version``.
  watch-docs               Watch both doc trees & rebuild them if files change.
  docs
      .browse              Open build target's index.html in a browser (using 'open').
      .build*              Build the API docs subsite.
      .clean               Nuke docs build target directory so next build is clean.
      .doctest             Run Sphinx' doctest builder.
      .tree
  release                  Python package release tasks.
      .all_*               Catchall version-bump/tag/changelog/PyPI upload task.
      .build               Build sdist and/or wheel archives, optionally in a temp base directory.
      .publish (.upload)   Publish code to PyPI or index of choice.
      .status              Print current release (version, changelog, tag, etc) status.
  www
      .browse              Open build target's index.html in a browser (using 'open').
      .build*              Build the main project website.
      .clean               Nuke docs build target directory so next build is clean.
      .doctest             Run Sphinx' doctest builder.
      .tree
```

Onwards and upwards to the depth & root selectors...

**Comment by bitprophet** [comment]
Also this reminds me I really need to figure out what happened to trimming trailing underscores in task names.

**Comment by bitprophet** [comment]
One downside with option 1 vs 2 above is that it's less consistent - w/o any alternate root, all task paths are fully explicit, and you need to use nested format to 'factor' things out. But then we give an alternate root, and suddenly, poof, we're no longer giving fully explicit paths.

However, most arguments I can think of for emphasizing consistency over "it looks nice / is readable / is obvious" boil down to "what if I was scripting something that is reading this?" - and as I've said a few times in here, one should be using the JSON format for that now.

**Comment by bitprophet** [comment]
Heh, another consequence of the "nice" factoring out of the given root, is that default tasks have no immediately obvious solution:

- With no root, they are simply displayed as the collection name: `build.all (build, build.everything)`
- In my example above, I uh...just omitted it entirely, so it's simply `.all (.everything)`, no indication that it's also the default task for `build`

But now that I am rubber ducking, I realize, aha: the obvious solution is to acknowledge that the current context is some specific collection, so we can just pull this out of the list entirely if we want - same as we probably _should_ be doing for the top level default task! (Which I don't think we currently highlight at all?)

E.g. stick it in the header line:

```
Available 'build' tasks (default: .all):

  .all (.everything)      Build all necessary artifacts.
  .c-ext (.ext)           Build our internal C extension.
  ...
```

Or on its own line between header and listing (tho then the colon is messy), or at the bottom of the listing (`If no specific task given, the default is: .all`, tho anything we put here is a bit verbose?) Or maybe rub some asterisks on it like we do for `nested`?

Gotta think about it.

**Comment by bitprophet** [comment]
Well, but not for long because I seriously don't have time for these fascinating weeds.

Putting it in the header does seem like the objectively cleanest approach for now, so I'mma do that.

**Comment by bitprophet** [comment]
JSON's done. Not super duper happy there either (eg ran into ye olde "list of objects with `name` keys, _or_ an object whose keys are the `name`s?" for example - went with my initial assumption, option 1, partly because it makes the recursive tree line up better) but it works and emits the same amount of data as one gets from the human-facing formats.

We can always beef that up more later if it seems desirable, though I'd assume anyone wanting to do deeper things on their own with collections/tasks would hopefully be wanting to just use the in-Python APIs.

**Comment by bitprophet** [comment]
As with most other new features, even depth is not as simple as it sounds:

- Until you get to depth limiting, everything else is predicated on showing _tasks only_, but once you start limiting by depth (esp in the case here where the point is to help users identify parts of the tree) you end up with list items which are _collections_.
  - Especially collections with no default task, since ones with default tasks are still arguably "tasks" in the sense that listing cares about.
- Because the output formats currently have no "language" for differentiating tasks from collections (because all list items [in flat] or all leaves [in nested] were tasks) I'm gonna have to make some up, or take a wholly different approach.
  - In addition, this feature really wants some sort of tally for collections whose contents are being filtered out, e.g. `build (2 tasks, 3 subcollections)` or whatever.

As for a "wholly different approach", I could throw out the idea of depth being a nice simple display dimension like format, and make an entirely separate listing command like `--list-namespaces` or `--list-collections` (kinda hate how this project has spawned so many inconsistent terminologies...). My guess is that even in deeply nested nontrivial task trees, showing the entire tree _but_ just the collections and none of the tasks (probably only task counts), would nearly always be sufficiently compact and readable.

@thinkwelltwd (or anyone else reading this) any thoughts here? I'm gonna go work on some other (more rote) tasks while this simmers in my brain, and extra input is welcome.

**Comment by bitprophet** [comment]
Still very on fence about this but gotta pick a road to go down. Hell, just writing this comment I've deleted like 3 different explanations of the pros/cons of either option. Will see what I can execute on quickest, we can always change later, now that JSON is a thing.

**Comment by thinkwelltwd** [comment]
I don't have specific suggestions to offer. But in general terms, I'd say favor the simplest implementation, requiring the user-specified fewest parameters. If it starts itching on really deep nesting, then the library user can always broaden instead of deepen their tasks / collections.  When that's no longer an option, there will likely be more details about how to improve presentation of namespaces & collections.

> I'm honestly tempted to axe the flat view entirely...

+1 Nested view is so much more intuitive and scalable. IMO, anything that hinders the implementation of nesting is worth eliminating.  

But then everybody's tastes vary so perhaps fixing flat format sorting would be better. If both flat/nested are retained, I agree the sorting should be identical.

**Comment by bitprophet** [comment]
Side note as I wrap this up, I don't see an obviously intuitive way to handle the conjunction of JSON format and the depth arg; the only thing that springs to mind is aping what I am doing with the other formats and changing the value of a truncated collection so its `tasks` and `collections` are integer counts/tallies instead of the actual sub-objects. (Or we use different keys entirely to avoid changing types [eg `tasks_count`], and have `tasks`/`collections` be empty lists.)

Just feels kinda wrong to me, esp insofar as depth limiting is more of a human facing "I cannot deal with too much information" and JSON format is arguably for computer consumption - that consumer should presumably be able to deal with truncating its display of the data on its end, if it's desired.

Also I'm lazy and running out of time. So I'm gonna have it just spit out an error instead of returning arguably-confusing truncated JSON data, for now. Can always enhance later.

**Comment by bitprophet** [comment]
Wow...it's done?! Jeez. Took longer than anticipated, as always, though I wasn't working on it at all last week.

Leaves some older flat-oriented task list code mostly vestigial (eg `Collection.task_names` and the recently-fixed sorting code for it, is now only used by the tab completion machinery) but whatever. Mostly != entirely.

Gonna do the CI dance and then pop this out as whatever the next pre-1.0 release number is...along a handful of other things that I think are sitting in the pipe.

**Comment by bitprophet** [comment]
0.23.0 is on PyPI with this change ![](http://i.somethingawful.com/forumsystem/emoticons/emot-toot.gif)
