### ISSUE TITLE
Watchdog and Invoke integration

### ISSUE THREAD

**Issue by wshayes** [pyinvoke/invoke#336]
https://github.com/gorakhargosh/watchdog (Python API and shell utilities to monitor file system events.) seems like it would be a perfect match with Invoke.  I don't see Watchdog embedded in Invoke as the right pattern.  What is the recommended way to integrate Watchdog with Invoke?

**Comment by bitprophet** [comment]
Thanks for the feedback!

Invocations actually has as basic watchdog module, see e.g. https://github.com/pyinvoke/invocations/blob/16dbf6d15773ade0f34b164e2117e6cc45d83528/invocations/testing.py#L47-L61 which relies on https://github.com/pyinvoke/invocations/blob/16dbf6d15773ade0f34b164e2117e6cc45d83528/invocations/watch.py

The tl;dr is that Invoke is the core task organizing / command running logic, and Invocations is common/blessed use case patterns built on top of Invoke.

Totally open to improvements in Invocations; it's been mostly my own stuff for now but once the project hits 1.0 and gets publicized more I expect more folks to submit PRs. (But I wouldn't reject any now, I just won't necessarily have time to prioritize them yet.)

**Comment by wshayes** [comment]
Thanks - completely missed this!
