### ISSUE TITLE
run output mangles some unicode characters

### ISSUE THREAD

**Issue by gregmuellegger** [pyinvoke/invoke#346]
When trying to print a unicode checkmark ✔, invoke mangles the output somehow and cannot display the resulting character.

I have the following tasks.py (using Python 2.7):
```python
# -*- coding: utf-8 -*-
from invoke import run, task

@task
def outtest():
    run(u'echo "✔"')
```

Here is the output:
```
$ inv outtest
���
```

It displays the checkmark correctly when I run the echo directly in the terminal:
```
$ echo "✔"       
✔
```

I'm using:
- Python 2.7
- invoke 0.12.2
- Arch Linux

**Comment by bsandrow** [comment]
This can be closed. I tested this on both `0.12.2` and `0.13.0`. I was able to reproduce this on `0.12.2` and it works correctly on `0.13.0`.

(I'll note that I had `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8` in my environment. Unsetting those variables causes Python to blowup over ascii encoding issues).

**Comment by bitprophet** [comment]
Thanks @bsandrow!

(Re: unsetting encoding vars - is that under Python 2 or 3?)

**Comment by bsandrow** [comment]
@bitprophet That was under Python 2.7. I didn't run the test under Python 3.x.
