### ISSUE TITLE
Test for self.args.list.value causes exception when a namespace is passed

### ISSUE THREAD

**Issue by IvanMalison** [pyinvoke/invoke#375]
The relevant line is here: https://github.com/IvanMalison/okcupyd/blob/754093e97b63a95f91adea13b509faf294cb3e18/.tox/py27/lib/python2.7/site-packages/invoke/program.py#L352

This seems to cause an issue when a Program with a namespace because task_args are not added when a namespace is passed in https://github.com/IvanMalison/okcupyd/blob/754093e97b63a95f91adea13b509faf294cb3e18/.tox/py27/lib/python2.7/site-packages/invoke/program.py#L98

**Comment by bitprophet** [comment]
Hrm, did you already nix that okcupyd repository, or is it private? I can't read it.

Either way, I think this duplicates #288. Closing for now, we can reopen if I'm wrong :)
