### ISSUE TITLE
Alternative syntax for task listing

### ISSUE THREAD

**Issue by tuukkamustonen** [pyinvoke/invoke#380]
Instead of `inv -l` giving out something like:

    bootstrap                   ...
    init.setup                  ...
    init.workon                 ...
    dev.clean                   ...
    dev.analyze                 ...
    dev.test                    ...
    dev.run                     ...
    doc.compile                 ...
    release.do                  ...
    deploy.create_env           ...
    deploy.update_env           ...
    deploy.delete_env           ...
    test.func                   ...
    test.perf                   ...

Wouldn't it be nice to get:

    bootstrap                 ...

    Init:
      setup                   ...
      workon                  ...
     
    Dev:
      clean                   ...
      analyze                 ...
      test                    ...
      run                     ...
    
    Doc:
      compile                 ...
    
    Release:
      do                      ...
    
    Deploy:
      create_env              ...
      update_env              ...
      delete_env              ...
    
    Test:
      func                    ...
      perf                    ...

The latter is more human-readable, although it requires more (vertical) console space. When you have lots of namespaces and tasks, you might want to enable it.

Maybe allow this through `inv -l --someparam`?

**Comment by bitprophet** [comment]
See #33 :)

**Comment by tuukkamustonen** [comment]
Uh, of course it already exists...
