### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by IvanMalison** [pyinvoke/invoke#382]
pyinvoke recently introduced breaking changes to its API WITHOUT bumping the major version number of the package.

This makes it incompatible with https://www.python.org/dev/peps/pep-0440/#compatible-release and python's general preference for the use of semantic versioning.

**Comment by tuukkamustonen** [comment]
I assume Jeff is not following semantic versioning, because the library is still in development phase and may be broken in several ways.

I am personally sticking to exact version now, for this specific reason.

**Comment by bitprophet** [comment]
Correct, it's not 1.0 yet, please notice the big red warning on the homepage - http://www.pyinvoke.org/

Post-1.0 it will absolutely honor semantic versioning. (In retrospect, the project was not expected to spend multiple years pre 1.0, or I would have started using semver earlier. 1.0 should actually not be super far off by now however.)
