### ISSUE TITLE
ctx missing in example in documentation

### ISSUE THREAD

**Issue by arighauks** [pyinvoke/invoke#388]
Hi, I didn't know how else to get this across so I'm posting here...

I believe there is an error in the documentation, on this page: http://docs.pyinvoke.org/en/0.13.0/getting_started.html it says:

```python
@task(help={'name': "Name of the person to say hi to."})
def hi(name):
    """Say hi to someone."""
    print("Hi %s!" % name)
```
but I believe the context variable (ctx) is missing in the function definition. Should be like this:
```python
@task(help={'name': "Name of the person to say hi to."})
def hi(ctx, name):
    """Say hi to someone."""
    print("Hi %s!" % name)
```

Thanks, and sorry if this is the wrong venue for posting this...

**Comment by bitprophet** [comment]
Fixed already in #363 - thanks!

You can see it live at http://docs.pyinvoke.org/en/latest/getting_started.html

I don't recall why the site was set to track latest tag; until 1.0 that's not as useful as just tracking 'latest', so for now I made 'latest' the default if one doesn't specify. Thanks for the nudge.
