### ISSUE TITLE
Instructions to install dev version don't work

### ISSUE THREAD

**Issue by rogual** [pyinvoke/invoke#391]
README says:
> You can install the development version via pip install invoke==dev --allow-unverified invoke

```
$ pip install invoke==dev --allow-unverified invoke
DEPRECATION: --allow-unverified has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
Collecting invoke==dev
  Could not find a version that satisfies the requirement invoke==dev (from versions: 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.13.0)
No matching distribution found for invoke==dev
```

```
$ pip --version
pip 8.1.2 from /usr/local/lib/python3.4/site-packages (python 3.4)
```

**Comment by bitprophet** [comment]
Looks like recent changes to PyPI made the `==dev` approach completely unworkable at long last. Thanks for bringing it to my attention!

Looks like the best alternative is to do `pip install -e` with the explicit repository URL, i.e. `pip install -e git+https://github.com/pyinvoke/invoke/#egg=invoke`. I'll update my README(s) with this.

**Comment by bitprophet** [comment]
Forgot to note in commit message, but: 9e1e85a68902c4e2fc481e7d39884c89ab93c2c3
