### ISSUE TITLE
docs: namespace.add_task(..., aliases=...) example does not work

### ISSUE THREAD

**Issue by jenisys** [pyinvoke/invoke#396]
VERSION: invoke-0.13.0 or newer (repo HEAD)
FILE: [sites/doc/concepts/namespaces.rst](https://github.com/pyinvoke/invoke/blob/master/sites/docs/concepts/namespaces.rst)

When you try the example that is described in the **Aliases** section:

``` python
ns.add_task(release, aliases=('deploy', 'pypi'))
```

it does not work because `Collection.add_task()` does not have an `aliases` parameter (or `**kwargs` argument). Note that the `@task` decorator still supports the `aliases` parameter.

SOLUTION (either / or):
- Fix the documentation related to `aliases`
- Provide the `aliases` parameter in the `Collection.add_task()` method again (?)

**Comment by bitprophet** [comment]
Thanks for the catch!

**Comment by bitprophet** [comment]
Not sure if it was added in response to this ticket, but the docs have a 'FIXME' comment specifically about this.

Since I was in there anyway, I fixed it. Hooray!
