### ISSUE TITLE
Explicitly calling task doesn't call the pre tasks defined in the decorator

### ISSUE THREAD

**Issue by alep** [pyinvoke/invoke#397]
I have a `clean` task (it's just an example) which I call explicitly from the `deploy` task (in my use I call the task clean depending on a condition, that's why I call it explicitly). 

What happens is that the task `clean` doesn't call `clean_html` and `clean_tgz`.

Am I misusing invoke? Thanks.

`tasks.py`

```python
from invoke import Collection, task, call
import clean

@task
def makedirs(ctx):
    print("Making directories")

@task(makedirs)
def build(ctx):
    clean.clean(ctx)
    print("Building")

@task(build)
def deploy(ctx):
    print("Deploying")

namespace = Collection(clean)
namespace.add_task(deploy)
```

`clean.py`
```python
from invoke import task

@task
def clean_html(ctx):
    print("Cleaning HTML")

@task
def clean_tgz(ctx):
    print("Cleaning .tar.gz files")

@task(clean_html, clean_tgz, default=True)
def clean(ctx):
    print("Cleaned everything")
```

**Comment by bitprophet** [comment]
Thanks for the report! You're not mis-using it, we just don't have a shorthand yet for "call this task in the same way the command-line runner does, honoring pre/post tasks". That's #170 - follow there. It's one of the bigger missing features; it will definitely get figured out before 1.0.
