### ISSUE TITLE
With pty=True, Failure.result.stderr is empty and Failure.result.stdout is populated

### ISSUE THREAD

**Issue by tuukkamustonen** [pyinvoke/invoke#400]
With:

```python
from invoke import run
from invoke.tasks import task
from invoke.exceptions import Failure


@task
def without_pty(ctx):
    try:
        run('asf')
    except Failure as e:
        print("STDOUT: " + e.result.stdout)
        print("STDERR: " + e.result.stderr)


@task
def with_pty(ctx):
    try:
        run('asf', pty=True)
    except Failure as e:
        print("STDOUT: " + e.result.stdout)
        print("STDERR: " + e.result.stderr)
```

Run:

```shell
$ inv without_pty with_pty
asf
/bin/bash: asf: command not found
STDOUT: 
STDERR: /bin/bash: asf: command not found

asf
/bin/bash: asf: command not found
STDOUT: /bin/bash: asf: command not found

STDERR: 
```

I don't know if this is intentional (=how terminals just work), but it feels a bit weird that with pty there is no stderr anymore, and that stdout is populated instead.

Feel free to close if this is just how terminals work...

Running invoke 0.13.0.

**Comment by bitprophet** [comment]
Yes, this is how terminals just work! See the warning under the 'pty' option in the docs for run(): http://docs.pyinvoke.org/en/latest/api/runners.html#invoke.runners.Runner.run

Sorry it bit you, I know it's unintuitive :) Wonder if we can make this easier to notice...maybe have `Result.stderr` access raise an exception (or at least emit a warning) if one accesses it when `pty=True`?

**Comment by tuukkamustonen** [comment]
Uh, no need to change anything - it is well documented, I just failed to RTFM :weary:.

And looks like I can detect if pty was really used via `Result.pty`, nice!
