### ISSUE TITLE
possible confusing documentation on MockContext (0.13.0 v 0.14.0 ?)

### ISSUE THREAD

**Issue by cbockman** [pyinvoke/invoke#417]
MockContext seems to be suggested as a testing solution (http://docs.pyinvoke.org/en/latest/concepts/testing.html#use-mockcontext), but--near as I can tell--is only 0.14.0.

'pip3 install invoke' will push out 0.13.0 (or at least does when I execute it).

Assuming I'm not stuck in some sort of version hell (i.e., a bad install on my end), this is unfortunate and probably undesirable--having documentation (and the API reference documentation, http://docs.pyinvoke.org/en/latest/api/context.html) pointing to development version, and not the standard install, is very confusing.

Again, maybe I just have a bad install....which I suppose would be a whole separate issue.

**Comment by bitprophet** [comment]
Something must be funky on your end because I see 0.14 on PyPI for both py2 and py3: https://pypi.python.org/pypi/invoke/0.14.0

Seems to work on my end too, via some not-super-old pip and Python and virtualenv versions (and via a local PyPI cache, but that's only a cache, nothing ever gets uploaded to it directly):

```
» mkv hm
New python executable in /Users/jforcier/tmp/hm/bin/python2.7
Also creating executable in /Users/jforcier/tmp/hm/bin/python
Installing setuptools, pip, wheel...done.
[11:28] hedron:~/tmp/hm {hm} [master]
» pi invoke==0.14
Collecting invoke==0.14
  Downloading http://localhost:3141/root/pypi/+f/502/2da278412a147/invoke-0.14.0-py2-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 61.1MB/s 
Installing collected packages: invoke
Successfully installed invoke-0.14.0
[11:28] hedron:~/tmp/hm {hm} [master]
» rehash
[11:28] hedron:~/tmp/hm {hm} [master]
» inv -V
Invoke 0.14.0
[11:28] hedron:~/tmp/hm {hm} [master]
» 
```

**Comment by bitprophet** [comment]
Gonna close as "probably not my fault" but obviously please keep posting if you figure it out or find more questions I can answer. Good luck!

**Comment by cbockman** [comment]
OK, looks like there were some weird settings on our end on how pip was going out and fetching things, and what it was reporting back.  Thanks for the quick cycle!  We do love the package!
