### ISSUE TITLE
Command echo is set fixed in a very hard to read grey

### ISSUE THREAD

**Issue by halloleo** [pyinvoke/invoke#424]
When I run a task with 

    ctx.run(command, echo=True)

the output is print hardcoded in the color grey - which is barely visible on white or grey backgrounds.

A way to customize this with a global variable would be great.

**Comment by bitprophet** [comment]
See #179 / #189! (I apparently never saw #189 til now; added it to a milestone so it has a chance of getting merged sometime. So thanks for the ping :))
