### ISSUE TITLE
python3 invoke doesn't add a context

### ISSUE THREAD

**Issue by SwampFalc** [pyinvoke/invoke#429]
So, in python3 it seems that the whole ctx mechanism isn't working properly...

```
@invoke.task
def set_ip(ctx, container, ip):
  ...
```

`inv -h lxc.set_ip` gives:
```
Options:
  -c STRING, --ctx=STRING
  -i STRING, --ip=STRING
  -o STRING, --container=STRING
```

`inv lxc.set_ip -o test -i 10.0.229.2` gives:

`'lxc.set_ip' did not receive all required positional arguments!`

invoke 0.14.0, python 3.5.2

**Comment by bitprophet** [comment]
Weird, I can't reproduce this on master/0.15.0, or on my 0.14.0 tag, with the following was-lying-around tiny task file:

``` python
from invoke import task

@task
def foo(c, cmd):
    c.run(cmd, pty=True)
```

If I try your exact style (where `@task` comes out of the module attribute-wise - which should not matter, but removing assumptions is troubleshooting 101...):

```
import invoke

@invoke.task
def foo(c, cmd):
    c.run(cmd, pty=True)
```

It still works fine, e.g.:

```
» inv -h foo
Usage: inv[oke] [--core-opts] foo [--options] [other tasks here ...]

Docstring:
  none

Options:
  -c STRING, --cmd=STRING
```

Can you post your full tasks tree (`tasks.py` or `tasks/__init__.py`, plus anything it imports)? There may be something else lurking that is the culprit.

**Comment by SwampFalc** [comment]
I just realised that this may be my own fault...

I first installed the official Ubuntu 16.04 invoke package (0.11), and then used pip to upgrade it to 0.14. I tried this exact setup again, though it updated to 0.15 this time, and I see the exact same result.

But this update process doesn't uninstall the 0.11:

```
Found existing installation: invoke 0.11.1
Not uninstalling invoke at /usr/lib/python3/dist-packages, outside environment /usr
```

So this is probably going to be caused by the fact that the executable is going to be 0.15, but it loads the 0.11 libraries which didn't have the ctx mechanism yet, right?

In which case, sorry for the bother and thanks for the assistance.

**Comment by bitprophet** [comment]
That sounds about right, yup. Mixing system and pip packages can easily lead to this kind of problem (for any Python package). You might not even really be loading anything but 0.11, depending on how your environment's PYTHONPATH is set up re: the system vs pip package locations. IIRC system usually 'wins' so you might not see the newer invokes until you uninstall the system package.

In my experience, usually folks who need to stick closer to the latest releases of software will just use system packaging to obtain Python and pip, then use pip for everything beyond that. Certainly my suggestion here :) good luck!
