### ISSUE TITLE
Upgrading from invoke 0.11.1 to 0.15.0

### ISSUE THREAD

**Issue by jredl-va** [pyinvoke/invoke#434]
While, this probably isn't an issue with invoke itself I'm mostly confused as to how to pass state between some fairly deep levels of interconnected tasks. 

We have been on 0.11.1 for a very long time and would like to upgrade. Version and environment information are computed within our build process and are set on the context config. However, with the newest version of invoke, it looks like context is now global across all tasks?

Is there a way to set a config / context option at runtime and have it available to a task further down the task chain?

EG:

```
@task()
def post_task(ctx):
    print ctx.config.environment

@task(post=[post_task])
def executor_task(ctx):
    ctx.config['environment'] = 'prod'
```

**Comment by jredl-va** [comment]
@bitprophet have any ideas on what I could try here?

**Comment by jredl-va** [comment]
Never mind found the issue I'm basically describing here: https://github.com/pyinvoke/invoke/issues/423

I can work around my issue by passing around pre / post tasks arguments: http://docs.pyinvoke.org/en/latest/concepts/execution.html#pre-post-tasks

**Comment by jredl-va** [comment]
Actually, it looks like I can't do what I want with .15.0 and pre-post task args. 0.11.1 is where I stay for now I guess. 

This is again mostly a duplicate of  https://github.com/pyinvoke/invoke/issues/309 capture

**Comment by jredl-va** [comment]
And my final comment on this closed issue....

Our invoke based build infrastructure has a singular task entry point in the form of a task. I was able to modify this task to simply call the subsequent tasks with the desired config, rather than relying upon pre / post task arguments.

My above example becomes:

```python
@task()
def post_task(ctx):
    print ctx.config.environment

@task()
def executor_task(ctx):
    ctx.config['environment'] = 'prod'
    post_task(ctx)

```

**Comment by bitprophet** [comment]
@jredl-va That last is currently what I do in my case, but I've found it breaks the ability to ever call those other tasks in the same session from the CLI (i.e. `inv executor_task post_task` instead of just `inv executor_Task`). Thus why #309 remains open. It's high on my list at this point since it's a visible wart and will affect an alpha of an upcoming higher level project that uses Invoke.

**Comment by jredl-va** [comment]
@bitprophet thanks for the feeback, I found that same thing myself. I ended up building a helper similar to this comment, that allows me to work around this: https://github.com/pyinvoke/invoke/issues/170#issuecomment-134927763
