### ISSUE TITLE
Bundle to single file with pyinstaller is not working

### ISSUE THREAD

**Issue by AlexShemeshWix** [pyinvoke/invoke#436]
Hi
Im on Mac OS Siera 10.12.23
Im using pyinstller 3.2
I have simple project 
Single file main.py with following content.
```
from invoke import Program
program = Program(version='0.0.1')
program.run()
```

I want to bundle it to single file. Im using pyinstaller
`pyinstaller -F main.py`

I can see dist folder and single executable in it.
But when i run it dist/main i get the error

```
Failed to execute script main
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from invoke import Program
ImportError: No module named invoke
```

ive added option for hidden-import

`pyinstaller --hidden-import=invoke -F main.py`

No luck.Still gives error.

My project suppose to be cli tool, i would prefer to pack it into single file.
What am i doing wrong?

**Comment by bitprophet** [comment]
Afraid I've never used pyinstaller so I'm not sure whether there's more we can do to be compatible with it. Does it not require Invoke (or any other library you import into your installer code) to be downloaded and installed via pip or similar?

Going to close this as "probably not a lot we can do w/o more info" but please comment if you find out more!
