### ISSUE TITLE
Exception raised in bytes_to_read() intermittently on windows

### ISSUE THREAD

**Issue by chrisc11** [pyinvoke/invoke#440]
On windows I occasionally hit this line https://github.com/pyinvoke/invoke/blob/master/invoke/platform.py#L162 and then hit an exception because `struct` is not imported for windows. However, the TODO on L159 suggests maybe code should never get there in the first place? Adding `or WINDOWS` on 160 seemed to resolve my issue

**Comment by bitprophet** [comment]
Yea, that's just an outstanding TODO, I was paranoid that maybe there was a corner case where some folks could be "on Windows" but still be able to run `ioctl`. Seems pretty darn unlikely.

It's funny that you're only getting it intermittently...I'd expect it to be a hard pass/fail. Perhaps it's only the times where you're triggering `has_fileno` by changing in/out streams, running with/without a pty, or similar.

Anyway, thanks for the report, I'll just slap that `or WINDOWS` in and we'll call it good.

**Comment by chrisc11** [comment]
Thanks!! Yeah, I was a little confused why it was intermittent as well. For what it's worth, the command that was failing for me was invoking pyserial/miniterm using ctx.run()
