### ISSUE TITLE
Override default tasks.py module name in invoke.yaml

### ISSUE THREAD

**Issue by dmulter** [pyinvoke/invoke#455]
I just migrated my Fabric setup over to Invoke, thanks a lot for the great work.

I've run into one issue that hopefully already has a solution. I'm using Celery across a number of apps and already have a tasks module. I've put my Invoke tasks in a invfile.py module and use the ```-c invfile``` option when I run invoke. Unfortunately that is not practical every time I run invoke.

I haven't found it, but is there a way I can specify the default module for invoke tasks in an invoke.yaml file in my app directory? Seems the most natural way to me.

**Comment by ploxiln** [comment]
If `invoke.yaml` is a standard named file for invoke to look for ... this just "kicks the can down the road" doesn't it? Can you just treat `tasks.py` as your `invoke.yaml`, the standard-named file that references custom files/paths?

**Comment by dmulter** [comment]
I don't think so about the can... ```invoke.yaml``` is very clearly in the invoke namespace, so it makes sense to me that I would configure something like the default module (tasks, or something else). Again, the ```tasks``` module is already used for my Celery tasks across many apps, so I can't call it tasks.py

**Comment by ploxiln** [comment]
Ah. I see that celery also recommends using "tasks.py" and that `invoke.yaml` is already a standard filename invoke looks for. Makes sense

**Comment by bitprophet** [comment]
Believe this duplicates #310, re: ability to tweak those low-level settings. Gonna merge this with that and put some updated thoughts in there, one sec.

**Comment by dmulter** [comment]
thanks!

**Comment by bitprophet** [comment]
@dmulter see https://github.com/pyinvoke/invoke/issues/310#issuecomment-313764522 :)
