### ISSUE TITLE
How to define the hosts to run tasks on? 

### ISSUE THREAD

**Issue by dclong** [pyinvoke/invoke#457]
For example, one can specify the hosts via `env.hosts` in Fabric. What's the equivalent in Invoke?

**Comment by Aiky30** [comment]
The hosts option in Fabric is for a ssh connection to a server. Invoke is just a task runner for your local machine, it is not intended to run tasks on a server.

This roadmap details this better: http://www.fabfile.org/roadmap.html

**Comment by dclong** [comment]
Get it. Thank you very much for the clarification!
