### ISSUE TITLE
Tasks with underscores in names no longer work

### ISSUE THREAD

**Issue by shyuep** [pyinvoke/invoke#468]
This is my tasks.py.

```
from invoke import task

@task
def build(ctx):
    print("build")

@task
def build_name(ctx):
    print("build_name")
```

`invoke build` runs fine. `invoke build_name` results in an error: `No idea what 'build_name' is!`.

This was working fine up to version 0.19.0 of invoke. It is a fairly critical error as it renders many of my previous tasks.py unworkable.

**Comment by fndari** [comment]
It appears that this was changed in version 0.20 (see [changelog](http://www.pyinvoke.org/changelog.html), or #329), but it can be reverted from as a configuration setting: http://docs.pyinvoke.org/en/latest/concepts/namespaces.html#dashes-vs-underscores

**Comment by shyuep** [comment]
Thanks.
