### ISSUE TITLE
When creating a custom invoke executable, what is the way to add parameters (global, not task specific)

### ISSUE THREAD

**Issue by ophiry** [pyinvoke/invoke#472]
specifically, I want to add a flag that will be used to specify an alternative execuotr

**Comment by bitprophet** [comment]
You probably want to override+extend [Program.core_args](https://github.com/pyinvoke/invoke/blob/master/invoke/program.py#L31) and then refer to your new arg elsewhere in Program. See for example how [this bit farther down](https://github.com/pyinvoke/invoke/blob/master/invoke/program.py#L504) references the core arg values for collection loading.

Closing as "no action needed" but not locking conversation. Thanks!
