### ISSUE TITLE
auto_dash_names: Should not be applied when a task is named

### ISSUE THREAD

**Issue by jenisys** [pyinvoke/invoke#478]
VERSION: invoke-0.21.0 or newer

When a user/task-writer explicitly names a task, this name should be available on the command-line to trigger that task (probably the same with ``aliases``). The user-supplied name is the preferred name of this task (and the user should stay in control).

```python
# -- FILE: tasks.py
from invoke import task

@task(name="hello-me")
def hello_me(ctx):
    pass  # SUPPRISE: Task name is converted to "hello_me" if auto_dash_names=false

@task
def hello_me2(ctx):
    # -- TASK-NAME DISCOVERY from function-name.
    #     FOLLOWS: auto_dash_names = false, true => hello_me2 or hello-me2
    pass
```

**Comment by bitprophet** [comment]
Should be obviated by #529 when implemented, please follow there!
