### ISSUE TITLE
Output from `ctx.prefix` commands wind up in out_stream

### ISSUE THREAD

**Issue by brandones** [pyinvoke/invoke#484]
Doing
```
with ctx.prefix('. $HOME/.nvm/nvm.sh && nvm use'):
    out_stream = StringIO.StringIO()
    ctx.run('npm pack gcommon/', out_stream=out_stream)
    print out_stream.getvalue()
```
yields
```
Found '/opt/gocmeniz/.nvmrc' with version <8.6>'
cd admin ; npm install ../Found '/opt/gocmeniz/.nvmrc' with version <8.6>
Now using node v8.6.0 (npm v5.3.0)
gcommon-1.0.0.tgz
```

While I'd really like it to just yield `gcommon-1.0.0.tgz`, i.e. the output from the command I've attached out_stream to.

**Comment by rpkilby** [comment]
Hi - just my two cents, but I'd argue that this is the correct behavior. Prefixing simply `&&`s the prefix commands to each command nested in the context - they aren't executed separately. eg, the executed command is the following:
```
. $HOME/.nvm/nvm.sh && nvm use && npm pack gcommon/
```

Additionally, you can always redirect the output of the prefix commands.

```python
with ctx.prefix('. $HOME/.nvm/nvm.sh && nvm use > /dev/null'):
    ...
```

**Comment by brandones** [comment]
This is certainly the correct behavior based on the existing implementation, which fortunately is stated pretty explicitly. But I'd argue that this is a surprising side-effect of the implementation, relative to what I'd expect the API to do independent of the implementation. I think the API would be less surprising if those streams didn't wind up together.

**Comment by bitprophet** [comment]
I get what you're going for, @brandones, but Ryan is right - this isn't naively possible without utilizing shell pipe redirection within each prefixed subcommand, and that's just as easy for users to do in their argument to `prefix` if and when they desire it.

I could _maybe_ see some argument for moving that functionality into `prefix` itself, e.g. `with prefix('some-very-verbose-command', hide=True): ...` which implicitly injects the equivalent of `&>/dev/null`. But it doesn't seem like that adds enough value to be worth the various expenses involved (code, time, etc) offhand. (It might fit later in some overarching "let's try to hide more shell things from users" feature set, maybe? But even that is kinda controversial - such features really want to truly add value over what users can do in the shell strings themselves.)
