### ISSUE TITLE
Run a script in background

### ISSUE THREAD

**Issue by ThibautSchmitt** [pyinvoke/invoke#490]
Hi,

I would like to know if it is possible to `run` a command in a background progress. Like on Linux with `&`.
I could do it with Fabric, but I don't know how to make it work with Invoke.

Example with Fabric:
```
    with lcd('./my/app'):
        local('python first.py&')
        local('python second.py')
```

And by mimicking it with Invoke, only the first script is running:
```
    with ctx.cd('./my/app'):
        ctx.run('python first.py&')
        ctx.run('python second.py')
```

I found a "workaround" by writing a `.sh` file where I wrote these 2 lines but I am not convinced about it. Is there a way to do so with Invoke ?

Thanks you.
Thibaut Schmitt

**Comment by haydenflinner** [comment]
`&` is a feature of your shell: Works for me with `pty=True` in the `run` call. Because of things like this, the first thing in all of my config files is this: `'run': { 'echo': True, 'pty': True}`

**Comment by tuukkamustonen** [comment]
Iirc, invoke attempts to auto-detect if your terminal is pty or tty(?)

**Comment by haydenflinner** [comment]
Do you mean set it according to whether or not you're calling invoke from a pty or tty? If it's supposed to, it doesn't work for me whether I'm in tmux/rhel or terminator/arch :smile:

**Comment by tuukkamustonen** [comment]
I think I'm confusing this with some other library. Invoke docs just say it defaults to tty: http://www.pyinvoke.org/faq.html#why-is-my-command-behaving-differently-under-invoke-versus-being-run-by-hand, nothing about auto-detection :/

I have also configured `pty: true` in `~/.invoke.yaml` on my workstation (but not in Jenkins).

**Comment by bitprophet** [comment]
Not sure why I didn't find this the other day, but I made #682 recently which covers this. As Tuukka noted, this isn't a thing with _remote_ Fabric but, unbeknownst to me, it actually functioned with _local_ Fabric, and continues to (sort of - thus that new ticket) work under Invoke.

Please follow #682 for a resolution on making this an actually-supported feature under Invoke/Fab2.
