### ISSUE TITLE
task name with underscore doesn't work properly

### ISSUE THREAD

**Issue by olexandr-klymenko** [pyinvoke/invoke#491]
Say we have a task
```
@task
def store_configs(_, host='consul', port=8500, conf_yml='consuled_conf.yml'):
    c = Consul(host, port)
    conf = yaml.load(open(conf_yml))
    for k, v in conf['configs'].items():
        c.kv[conf['prefix'] + '/' + k] = v
```
if I run <b>invoke store_configs</b>, the following error shows up:
```
No idea what 'store_configs' is!
```

in order to invoke it I must do following:
```
invoke store-configs
```
Which isn't obvious. I think there are two option:
1. Fix it so that we cat run command with underscore which is preferable
2. Create explisit note in documentation

**Comment by olexandr-klymenko** [comment]
BTW, it used to work in prevous versions

**Comment by tuukkamustonen** [comment]
The behavior was intentionally changed (I think in 0.20.0). Can't comment on reasoning. Anyway, if you want to restore the original behavior, there is `auto_dash_names` flag that you can disable. For example in `~/.invoke.yaml`:

    tasks:
        auto_dash_names: false

Be sure to use 0.20.2+ for there was a bug regarding this option (https://github.com/pyinvoke/invoke/issues/465).
