### ISSUE TITLE
How to pass data between tasks

### ISSUE THREAD

**Issue by marcdexet-cnrs** [pyinvoke/invoke#492]
Hello

I have a kind of silly question.

How can I pass data between tasks. Context doesn't seem to support storage

In the silly use case, I get a producer and a consumer.

How producer can furnish consumer ?

```python
@task
def build_something(ctx):
    high_value =  build_an_high_value_object()
    # store high_value somewhere in context

@task(pre=[build_something, build_something_else]
def use_high_value_object(ctx):
    high_value = #extract high_value from context
```

The only one way I found it to make a global storage, but in my humble opinion, it breaks the concept of passing context to each task.

```python

storage = {}
@task
def build_something(ctx):
    high_value =  build_an_high_value_object()
    storage['high_value'] = high_value

@task(pre=[build_something, build_something_else]
def use_high_value_object(ctx):
    high_value = storage['high_value'] 
```
Do I have missed something ?

Thanks for your time and pyinvoke !

**Comment by pts-rajperera** [comment]
I've done things like this with invoke. I'm not sure if its the best approach.

```python
@task
def build_something(ctx):
    ctx.config.highvalueobject =  build_an_high_value_object()


@task
def use_high_value_object(ctx):
    build_something(ctx)
    build_something_else(ctx)
    high_value = ctx.config.highvalueobject #extract high_value from context
```

**Comment by marcdexet-cnrs** [comment]
@pts-rajperera thanks.

I was thinking the same, but it's pretty confusing to put a non-config object into config dict. :)

**Comment by SwampFalc** [comment]
What's the reason that your build_something is a task?

Because if the only thing it does is prepare an object to be used by the actual task, then I would leave build_something as a normal python function which returns your object...

**Comment by SwampFalc** [comment]
And I almost forgot: even tasks are still python function so they can return things.

**Comment by bitprophet** [comment]
This is basically asking for #170, I think :) it's not fully solved yet but is one of the higher priority items blocking a 1.0 release! Keep an eye on that ticket :)

FWIW, @pts-rajperera isn't wrong, stuffing your own data into the context/config that's passed around, is currently a valid option. It's not clearly documented / tutorialed yet just because ideally there will be a more straightforward option sometime.

**Comment by jamiet-msm** [comment]
Hi @bitprophet 
Apologies for returning to an old thread...
You said there

> ideally there will be a more straightforward option sometime.

Four years later... does that "more straightforward option" now exist?

Reason for asking is I wrote some tasks yesterday where a pre task derives a `version` based on a git commit ref and I want to refer to that `version` in my `build` & `publish` tasks so I store `version` in `ctx.version` and refer to it when needed.

Seems to work fine but I'm worried that:
- Passing data between tasks is somewhat of an anti-pattern and/or..
- There might now be a better way to pass data between tasks

Would appreciate your opinion on this.

**Comment by red8888** [comment]
> I've done things like this with invoke. I'm not sure if its the best approach.
> 
> ```python
> @task
> def build_something(ctx):
>     ctx.config.highvalueobject =  build_an_high_value_object()
> 
> 
> @task
> def use_high_value_object(ctx):
>     build_something(ctx)
>     build_something_else(ctx)
>     high_value = ctx.config.highvalueobject #extract high_value from context
> ```

This didn't work for me when running tasks with `pre` like this:

> ```python
> @task
> def build_something(ctx):
>     ctx.config.highvalueobject =  build_an_high_value_object()
> 
> 
> @task(pre=[build_something])
> def use_high_value_object(ctx):
>     build_something(ctx)
>     build_something_else(ctx)
>     high_value = ctx.config.highvalueobject #extract high_value from context
> ```

For me that returned a key error.
