### ISSUE TITLE
Help requested with a task that doesn't terminate

### ISSUE THREAD

**Issue by SwampFalc** [pyinvoke/invoke#495]
I'm aware that the following might not be a true invoke issue, but I don't really know where else I could get some help.

I have a control script for a piece of software. Call it with a 'start' parameter to start the whole kit and caboodle, or 'stop' to do the reverse.

I use invoke to drive my backups and I need to stop this thing so I can make a clean backup and then start it again.

So I have two small invoke tasks to stop and start it. Both are just one line: ctx.run('/opt/testlink/controlscript start') or 'stop' as is the case.

Except that the start task doesn't finish. It starts up all the application processes but then it's just waiting for something... and I need to kill the invoke process to get it to end.

And of course, running the script itself from the command line works fine. Which of course leaves me with little to nothing to actually go on.

I've tried pty=True, I've tried shell=/bin/sh, nothing seems to make a difference. I've downgraded invoke all the way to 0.18.1 because I saw issue #463 and it miiiight have been the same, but to no avail. 

Does anyone have a clue what I could try?

**Comment by SwampFalc** [comment]
So I tried a bit of gdb, even though I'm far from fluent.

Seems that the code ends up stuck in a sem_wait() loop? A quick bit of googling shows there might be a race condition between threads, leading me to believe that the underlying script I'm trying to run (some basic /bin/sh stuff even...) is not thread safe.

So the question becomes is there a way to make ctx.run() not do threading, or to somehow make it aware it's going to be running something not thread-safe?

Or is it likely I'll need to do a subprocess call instead?

**Comment by SwampFalc** [comment]
Alright, some more info.

I tried subprocess.

Subprocess.check_output gave me basically the same result: a hung process.

Subprocess.call did terminated fine.

So I'm guessing there's some I/O issue that works fine if no-one messes with stdout/stderr, but that stops the process from closing properly if someone did...

**Comment by haydenflinner** [comment]
Cleanest fix that might work?:
```
        from io import StringIO
        # if you had a shell that had to be started and then have start written
        # into it, you could do 
        # eof_stream = StringIO(u'start\n\x03')
        eof_stream = StringIO(u'\x03')
        ctx.run('cmdhere', pty=True, in_stream=eof_stream)
```

Have you tried with `pty=True` and appending `&` to the end of the command? You won't know if the start program ever exits, it might stay running and just be sitting around in the background, but that might not be a problem in your case. There's also `pgrep` and `kill` :wink: . You could also set the run call to ignore failure, as it looks like invoke catches CTRL+C's and passes them through. Then running your tool would require an extra key press each time :smile:

**Comment by bitprophet** [comment]
This may be a bug around non-mirrored stdin, #552 is so far one of the deeper digs at the issue, consolidating there.
