### ISSUE TITLE
sys.path configuration

### ISSUE THREAD

**Issue by dj-foxxy** [pyinvoke/invoke#501]
I have a module of utility functions (e.g., `install_packages(ctx, *packages)`) that lives in the root of the repository. This module is used by `tasks.py`s in each project directory, e.g.:

```
repo
├── proj_1
│   └── tasks.py
├── proj_2
│   └── tasks.py
├── proj_3
│   └── tasks.py
└── util.py
```

**What's the easiest way to get `util.py` on the `sys.path` when a `tasks.py` is executed?**

At the moment, I have this boilerplate at the top of each `tasks.py`:

```
import os
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent / '..'))
from util import *
```

**Comment by chenull** [comment]
make another project `proj4`as a python package then do

```python
from proj4.utils import *
```
i saw this kind of method is done by the author, see [invocations](https://github.com/pyinvoke/invocations)

maybe another approach is to sublclass `Loader` from invoke's `loader.py` so that all project's `tasks.py` can be loaded at once.

Both methods are what i've done inside my own project when using `invoke`

**Comment by dj-foxxy** [comment]
@chenull Thanks for the reply. I can't seem to get your suggestion working. I created:

```
test1
└── tasks.py
test2
└── __init__.py
```
But `invoke` cannot find `test2`:
```
$ cd test1
$ invoke -l
...
ModuleNotFoundError: No module named 'test2'
```

**Comment by AvihayTsayeg** [comment]
did you try adding __init__ under  repo (root dir)

**Comment by chenull** [comment]
what i meant by a python package, is an installable/uninstallable python app. something like `django` or `invocations`. a tutorial is available on [pypa docs](https://packaging.python.org/tutorials/distributing-packages/). For an easy creation of a python package, i usually use [hatch](https://github.com/ofek/hatch), and for development process i usually use [pipenv](https://github.com/pypa/pipenv/).

This `tree` is what i currently have:

```shell
.
├── istimewa
│   ├── Pipfile
│   ├── Pipfile.lock
│   ├── tasks.py
│   └── tests
├── liur
│   ├── Pipfile
│   ├── Pipfile.lock
│   ├── infra
│   └── tasks.py
├── senggani
│   ├── Pipfile
│   ├── Pipfile.lock
│   ├── logs
│   └── tasks.py
├── umbulharjo
│   ├── Pipfile
│   ├── Pipfile.lock
│   └── tasks.py
└── vape
    ├── Pipfile
    ├── Pipfile.lock
    ├── setup.py
    ├── tests
    ├── vape
    └── vape.egg-info
```

here, the `vape` package is one which will be imported to other projects, `vape` is listed in a `Pipfile` file for every projects which have `tasks.py`

**Comment by dj-foxxy** [comment]
Since opening this issue, I've played with a few solutions have a stuck with creating and installing an editable python package in root of the repo. E.g.

```shell
$ cd $repo/tasklib
$ pip install --user --editable .
$ cd $repo/proj
$ cat tasks.py
from invoke import task

import tasklib

@task
def clean(ctx):
    tasklib.clean(ctx, __file__)
```
