### ISSUE TITLE
Allow ctx.run() to tale a list as the command to run

### ISSUE THREAD

**Issue by pfmoore** [pyinvoke/invoke#514]
When writing a cross-platform task, it can sometimes be tricky to get quoting correct. An example from the pip build process:

```python
r = ctx.run("git log --use-mailmap --format'=%aN <%aE>'", encoding="utf-8", hide=True)
```

This works on Unix, but breaks on Windows (where single quote is not supported by the shell). Being able to write this in the form of an argv list:

```python
r = ctx.run(["git", "log", "--use-mailmap", "--format=%aN <%aE>"], encoding="utf-8", hide=True)
```

would increase portability and reduce the risk of people not familiar with both platforms messing up the quoting. (The class `invoke. runners.Local` uses `subprocess.Popen` to implement `run()`, at least in the non-pty case, and that supports argv lists in a cross-platform manner).

**Comment by bitprophet** [comment]
See #2 :)

Also in trying to find #2 I found an extant PR for this, and linked it therein. Do comment (over there!) if you're able to give it a spin, I haven't looked it over yet.
