### ISSUE TITLE
add "confirm" function

### ISSUE THREAD

**Issue by plockaby** [pyinvoke/invoke#523]
I read the documentation on upgrading from Fabric 1.x and it says to use "invocations" to get the "confirm" functionality. So I went to install "invocations" and it installed babel, pygments, sphinx, sphinxcontrib, alabaster, blessings, docutils, enum, enum34, imagesize, releases, semantic_version, snowballstemmer, tabulate, and tqdm as dependencies. All that to get a function that doesn't actually use any of those dependencies and just asks a question. Please consider just putting "confirm" into the invoke library else I will likely just end up writing my own "confirm" function and sprinkling it where I need it. Thanks for considering!

**Comment by bitprophet** [comment]
Thanks for the input, but those are all 100% pure Python libraries. Installing Python libs is part and parcel of any development and distribution process that isn't "100% stdlib". I'd understand if they were C extensions, but they're not. We'll have to agree to disagree here.

**Comment by bitprophet** [comment]
Later waffling: I was just reminded that `pip install library[flavor]` is a thing – so if there's a way to handle the actual "optional" imports without it being too annoying (it being a mostly annoying, warning-spewing kludge is one reason we didn't bother much before 1.0) that could be one way to make invocations easier to use. I've recorded this over on the right tracker as pyinvoke/invocations#11. thanks!
