### ISSUE TITLE
Mutation of config-attached object does not survive task lifecycle

### ISSUE THREAD

**Issue by NathanRichard** [pyinvoke/invoke#535]
Hello,
I am new to pyinvoke so maybe I am missing something trivial, but I did not find anything in the doc regarding this issue and I find it very counter-intuitive.

As I understand the Invoke API, one of the goal of Context.config is to manage state of the execution and pass it between tasks.

However when I run the following code:

```
#!/usr/bin/env python3

from invoke import Collection
from invoke import task
class struct:
	def __init__(self):
		self.state = 1

	def mutate(self):
		self.state = 2

@task
def initStep(ctx):
	ctx.val = struct()
	print("initStep ", ctx.val.state)

@task(initStep)
def mutStep(ctx):
	ctx.val.mutate()
	print("mutStep ", ctx.val.state)

@task(initStep, mutStep)
def clientStep(ctx):
	print("clientStep ", ctx.val.state)

```
I got the following output:

```
$ inv clientStep 
initStep  1
mutStep  2
displayStep  1
```

While I expected:

```
initStep  1
mutStep  2
displayStep  2
```

Could you please advise if it is intended or a bug ?

Best regards,
Nathan

**Comment by bitprophet** [comment]
Please see #261, this functionality doesn't work super well at the moment, but we would like it to (as you said: it is a goal. it's a goal we haven't met yet!) Thanks!
