### ISSUE TITLE
Allow configuration file to be specified by an environment variable

### ISSUE THREAD

**Issue by kevinjqiu** [pyinvoke/invoke#543]
Similar to how `kubectl` loads configuration files, if `KUBECONFIG` environment variable is set, it will load that config file as opposed to `$HOME/.kube/config`.

We have a few CLI scripts built on top of invoke, and we'd like the ability to specify config files during runtime.

e.g., suppose our CLI needs to talk to different servers for different environments,

```
inv -f dev.yaml <command>
inv -f prd.yaml <command>
```

we'd like to have the ability to do:
```
export INV_CONFIG=$(pwd)/dev.yaml
inv <command>
```

@bitprophet if you think this is a worthy feature, I wouldn't mind contributing a PR.

Thanks for pyinvoke!

**Comment by bitprophet** [comment]
All set, is now the `INVOKE_RUNTIME_CONFIG` env var, let me know how it looks! Will go out in the 1.1 release. Kinda want to tackle at least one more real feature before I put that on PyPI. Hopefully soonish.

**Comment by kevinjqiu** [comment]
@bitprophet Thanks for the quick turnaround.  One request: can we config the env var that invoke looks for? We [customize invoke](http://docs.pyinvoke.org/en/1.0/concepts/library.html#reusing-invoke-s-cli-module-as-a-distinct-binary) to build our CLI with a different name, and it'd be nice to have the environment variable reflect our CLI's name.

e.g., if our CLI is `awesome`, the env var we'd like `awesome` to look for is `AWESOME_CONFIG`.

Thanks!

**Comment by bitprophet** [comment]
You can! See http://docs.pyinvoke.org/en/1.0/concepts/library.html#changing-filenames-and-or-env-var-prefix

**Comment by kevinjqiu** [comment]
But as you said, the `INVOKE_RUNTIME_CONFIG` is a "regular env var" unlike the late-binding env vars.  I tried the `tester` program on master with the latest `RUNTIME_CONFIG` feature, setting `TESTER_RUNTIME_CONFIG` (after using a specialized `Config` class with prefix set to `tester`) didn't work:

```
$ tree
.
|____setup.py
|____tester
| |____tasks.py
| |____main.py
|____config.yaml
```
```
$ cat tester/main.py 
from invoke import Program, Collection, Config
from tester import tasks

class TesterConfig(Config):
    prefix = 'tester'


program = Program(version='0.1.0',
                  namespace=Collection.from_module(tasks),
                  config_class=TesterConfig)
```
```
$ cat tester/tasks.py 
from invoke import task


@task
def hello(ctx):
    print('Hello world: {}'.format(ctx.config.foo))
```

```
$ cat config.yaml 
foo: bar
```

```
$ tester -f config.yaml hello
Hello world: bar
$ export INVOKE_RUNTIME_CONFIG=$(pwd)/config.yaml
$ tester hello
Hello world: bar
$ unset INVOKE_RUNTIME_CONFIG
$ export TESTER_RUNTIME_CONFIG=$(pwd)/config.yaml
$ tester hello
Traceback (most recent call last):
  File "/home/kevin/src/invoke/invoke/config.py", line 112, in __getattr__
    return self._get(key)
  File "/home/kevin/src/invoke/invoke/config.py", line 177, in _get
    value = self._config[key]
KeyError: 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin/src/invoke/.env/bin/tester", line 11, in <module>
    load_entry_point('tester', 'console_scripts', 'tester')()
  File "/home/kevin/src/invoke/invoke/program.py", line 335, in run
    self.execute()
  File "/home/kevin/src/invoke/invoke/program.py", line 491, in execute
    executor.execute(*self.tasks)
  File "/home/kevin/src/invoke/invoke/executor.py", line 134, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/kevin/src/invoke/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/home/kevin/src/invoke/tmp/tester/tasks.py", line 6, in hello
    print('Hello world: {}'.format(ctx.config.foo))
  File "/home/kevin/src/invoke/invoke/config.py", line 124, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'foo'

Valid keys: ['run', 'runners', 'sudo', 'tasks']

Valid real attributes: ['clear', 'clone', 'env_prefix', 'file_prefix', 'from_data', 'global_defaults', 'load_base_conf_files', 'load_collection', 'load_defaults', 'load_overrides', 'load_project', 'load_runtime', 'load_shell_env', 'load_system', 'load_user', 'merge', 'pop', 'popitem', 'prefix', 'set_project_location', 'set_runtime_path', 'setdefault', 'update']
```

**Comment by bitprophet** [comment]
Sorry, for some reason I'd interpreted what you said as a generic question instead of a specific followup – you're right, that new env var we just added is hardcoded, I'll make a new ticket for making it configurable. (Smells a little off -- think it may want tighter tie-in with how Program and Config interact re: env vars and prefixes -- but still something to put down as a nice-to-have.)
