### ISSUE TITLE
Prefix echo'd commands and output with task name

### ISSUE THREAD

**Issue by OddBloke** [pyinvoke/invoke#546]
I'm composing a few tasks together, and I'd like for my users/fellow developers to understand what's happening when. _Ideally_ I'd like something like (assuming invented clean and build tasks):

```
[clean] rm -rf build/
[clean] echo "very clean"
[clean] very clean
[build] make build
[build] multi-line
Makefile
output
(which could be prefix'd but I don't mind)
```

**Comment by bitprophet** [comment]
This seems like it falls under #15 since the intent is the same - log as much info as possible in a manner that allows users to opt-in or opt-out of the level of detail. Going to roll into that. I just added a section with use cases in the description, jogged by this and the other ticket. Thanks!
