### ISSUE TITLE
Indicate task lifecycle in output

### ISSUE THREAD

**Issue by OddBloke** [pyinvoke/invoke#547]
In a similar vein to #546, I'd like users to know when a task starts running and when it completes, so they better understand how execution is happening:

```
Executing `clean` task
rm -rf build/
echo "very clean"
very clean
Execution of `clean` task complete
Executing `build` task
make build
Makefile
output
Execution of `build` task complete
```

Some sort of colour-based indication of the status would make the above easier to parse.

**Comment by bitprophet** [comment]
Rolling this into #15 for same reasons.

**Comment by OddBloke** [comment]
Thanks @bitprophet!
