### ISSUE TITLE
Problem passing environments variables with sudo.

### ISSUE THREAD

**Issue by mhubig** [pyinvoke/invoke#572]
A common use case for me, is to pass some environment variables as dict to `run()`. Using this pattern with `sudo()` fails. I feel like this is a unexpected behavior which leads to a lot of confusion!

```bash
$ c.run('env |grep TEST', env={"TEST": "ENVIRONMENT"})
TEST=ENVIRONMENT
```
```bash
$ c.sudo('env |grep TEST', env={"TEST": "ENVIRONMENT"})
```

I know I can get around this by using:

```bash
$ c.run('sudo -E env |grep TEST', env={"TEST": "ENVIRONMENT"})
TEST=ENVIRONMENT
```

I think a good way to solve this would be to add a flag to the `sudo()` command, e.g. like this:
```bash
$ c.sudo('env |grep TEST', env={"TEST": "ENVIRONMENT"}, pass_env=True)
TEST=ENVIRONMENT
```
Or maybe to automatically add the `-E` Flag to sudo if env is passed?

**Comment by bitprophet** [comment]
Yea I think given this is specific to sudo's internal behavior around env vars, I'm gonna say this falls under #540 for the time being. That said I could see us _maybe_ adding some automagic behavior around enabling `-E` when env is in play, later on? Or perhaps making `-E` part of the default set (though this would require some security review and my gut says it's not a good idea). So this may get reopened later. Thanks!
