### ISSUE TITLE
__pycache__ directory included in source tarball

### ISSUE THREAD

**Issue by mjpieters** [pyinvoke/invoke#586]
The 1.2.0 release up on PyPI contains python bytecode in the source tarball:

 ```
$ mkdir /tmp/invoke-dl/ && cd /tmp/invoke-dl
$ wget https://files.pythonhosted.org/packages/ef/80/cef14194e2dd62582cc0a4f5f2db78fb00de3ba5d1bc0e50897b398ea984/invoke-1.2.0.tar.gz
$ tar xzf invoke-1.2.0.tar.gz
$ find invoke-1.2.0 -name \*.pyc
invoke-1.2.0/invoke/completion/__pycache__/complete.cpython-36.pyc
invoke-1.2.0/invoke/completion/__pycache__/__init__.cpython-36.pyc
```

These are, transitively, included in the wheel files too.

Please make sure to not include `__pycache__` directories in the source tarball.  I suspect that it ends up in the source tarball due to the following line in `MANIFEST.in`: https://github.com/pyinvoke/invoke/blob/e4bbd9b0d03cb3dbbbe2d8094f6d84a31fe51ed5/MANIFEST.in#L4

😞 

I suspect that all it takes is to add

```
recursive-exclude * __pycache__
recursive-exclude * *.py[co]
```
to `MANIFEST.in` to prevent this.

**Comment by bitprophet** [comment]
Grumpy that I missed this when it was first posted. Will try to get this fixed for the upcoming bugfix releases.

**Comment by bitprophet** [comment]
Huh, well this may explain it, I can't actually reproduce this on my end (macOS 10.14, Python 3.7). E.g. on master today:

```
» python setup.py sdist
...
» tar tzvf dist/invoke-1.4.0.tar.gz | egrep -v '(\.(py|ya?ml|json|rst|txt|cfg|css)|/)$'               
-rw-r--r--  0 jforcier staff    1314 Jan 24 15:30 invoke-1.4.0/LICENSE                                
-rw-r--r--  0 jforcier staff     273 Jan 10 11:34 invoke-1.4.0/MANIFEST.in                            
-rw-r--r--  0 jforcier staff    2078 Jan 29 12:07 invoke-1.4.0/PKG-INFO                               
-rw-r--r--  0 jforcier staff    1356 Jan 10 11:34 invoke-1.4.0/invoke/completion/bash.completion      
-rw-r--r--  0 jforcier staff     382 Jan 10 11:34 invoke-1.4.0/invoke/completion/fish.completion      
-rw-r--r--  0 jforcier staff    1429 Jan 10 11:34 invoke-1.4.0/invoke/completion/zsh.completion       
-rw-r--r--  0 jforcier staff    2078 Jan 29 12:07 invoke-1.4.0/invoke.egg-info/PKG-INFO               
-rw-r--r--  0 jforcier staff       0 Feb  4  2017 invoke-1.4.0/tests/_support/ignoreme/ignoremetoo/.no
```

No pyc's, no pycache's. Our MANIFEST.in still doesn't strip them out though (per #604) so I'm wondering what in my process could have added such things earlier, if it's not doing so now.

At any rate, I'll still merge #604 and that should ensure this doesn't recur. Should go out as Invoke 1.3.1 and 1.4.1. Thanks for the report.
