### ISSUE TITLE
@task(help={...}) should be dash/underscore agnostic

### ISSUE THREAD

**Issue by tuukkamustonen** [pyinvoke/invoke#590]
This doesn't work:

```python
@task(help={'foo_bar': '...'})
def some_task(ctx, foo_bar):
    ...
```

This works:

```python
@task(help={'foo-bar': '...'})
def some_task(ctx, foo_bar):
    ...
```

It's kinda confusing that you need to use the dashed syntax in `help`, while the parameter is really named with underscore.

**Comment by haydenflinner** [comment]
#580

**Comment by tuukkamustonen** [comment]
And original tickets are #409 and #533 as pointed out in the PR. Closing this one!
