### ISSUE TITLE
Feature request: allow setting variables from other variables

### ISSUE THREAD

**Issue by kenden** [pyinvoke/invoke#594]
# Feature request: allow setting variables from other variables

Using a Makefile, it is quite common to create variables from other variables, like this for example
```bash
DOCKER_REPO_IMAGE_TAG := ${DOCKER_REPO} + '/' + ${DOCKER_IMAGE} + ':' + ${DOCKER_TAG}
```

I found it hard to do the same thing using invoke.
Using a [Collection](http://docs.pyinvoke.org/en/1.2/concepts/configuration.html#collection-based-configuration), we can create simple variables:
```python
ns = Collection(mylocaltask, docs)
ns.configure({'sphinx': {'target': "built_docs"}})
```
but we cannot get any of the variables in the environment
(`ns.configuration()` returns empty).

The only way I found is to have a task that will set variables:
```python
@task()
def set_run_env_vars(ctx):
    """Set the environment variables to be used by scripts
    Most environment variables come from the environment or the invoke.yml files,
    but some need to be computed."""
    ctx.env['WORKSPACE'] = os.getenv('WORKSPACE', 
                                      os.path.dirname(os.path.realpath(__file__)))
    ctx.env['DOCKER_REPO_IMAGE_TAG'] = '%s/%s:%s' % (ctx.env.DOCKER_REPO, 
                                                     ctx.env.DOCKER_IMAGE, 
                                                     ctx.env.DOCKER_TAG)
```
and call that function from other tasks.
```python
@task(set_run_env_vars)
def build_docker_image(ctx):
    """Build the docker image"""
    ctx.run('%s/utils/build_image %s/%s %s' % (ctx.env.WORKSPACE, ctx.env.WORKSPACE,
                                               ctx.env.FOLDER_NAME,
                                               ctx.env.DOCKER_REPO_IMAGE_TAG))
```

I would be nice to have an easier way to do this. The amount of extra code needed compared to make is pretty big.

**Comment by haydenflinner** [comment]
I've been using .py files for config, so when the invoke.py config file is imported, I first set up workspace, mkdir it, then programmatically generate other options like repo_image_tag, all sequentially in the .py config file.

Eventually, my generating of a config from around 10 lines of actual config got so long that I broke invoke.py into two pieces -- The big piece, which is still loaded by invoke, and a `custom_config.py/yaml/json` that I load from my main invoke.py.

I'm not sure that it will save a lot of typing for you, though, as Python will almost never be as succinct as Make, given that it will also never be so cryptic or poorly understood by those not familiar.

**Comment by kenden** [comment]
@haydenflinner thanks for the answer!
I tried using `invoke.py` instead of `invoke.yml`.
This does work !
```python
# in invoke.py
DOCKER_REPO = "my-docker-repo.myserver.com"
DOCKER_IMAGE = "my-image"
DOCKER_TAG = "v1.1"
DOCKER_REPO_IMAGE_TAG = DOCKER_REPO + '/' + DOCKER_IMAGE + ':' + DOCKER_TAG
```

However I can't use this file to set up `WORKSPACE`

When adding this to invoke.py:
```python
import pathlib
WORKSPACE = pathlib.Path(__file__).resolve().parent
```

it results in a faillure with:
```bash
invoke.exceptions.UnpicklableConfigMember: 'pathlib' is a module, which can't be used as a config value. (Are you perhaps giving a tasks file instead of a config file by mistake?)
```

Which means I still need a task to set it up:
```python
def set_workspace_env_var(ctx):
    ctx.env['WORKSPACE'] = os.getenv('WORKSPACE', Path(__file__).resolve().parent)
```

**Comment by haydenflinner** [comment]
Sorry to be even hackier -- you can move that task to your invoke.py, and import pathlib from within the function. Or you can import the module as __pathlib to have it ignored in the process of loading invoke.py!
