### ISSUE TITLE
Issue with Python subprocess printing Unicode characters on Windows

### ISSUE THREAD

**Issue by pfmoore** [pyinvoke/invoke#595]
As of version 3.6 on Windows, Python has been able to print the full Unicode character set to the console, even if the current console code page doesn't include those characters (see [the announcement here](https://docs.python.org/3.7/whatsnew/3.6.html#pep-528-change-windows-console-encoding-to-utf-8)).

Invoke crashes when a Python subprocess prints Unicode. Here's a reduced example:

tasks.py:

```python
from invoke import task

@task
def test(c):
    c.run('''py -3.7 -c "print('\U0001f52a')"''')
```

Interactive session

```
>inv test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\UK03306\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f52a' in position 0: character maps to <undefined>
PS 15:25 {00:01.707} C:\Work\Scratch\invissue\1
>py -3.7 -c "print('\U0001f52a')"
🔪
```

Even if correctly printing the Unicode character is difficult to achieve, Invoke shouldn't crash in this situation (replacing the unprintable character with a substitute would be sufficient as a workaround in the short term).

**Comment by pfmoore** [comment]
This isn't actually an issue with Invoke - when run from `context.run()`, Python's output is being sent to a pipe, and so it's using the normal Windows encoding, not UTF-8. So printing characters that can't be encoded fails.

It might be worth a documentation note clarifying that output is to a pipe and then written to the console, and not directly to the console - but to be fair, even if there were such a note I wouldn't have read it in this situation :wink:

**Comment by Kilo59** [comment]
@pfmoore 
Is this something that could be "solved" by capturing/hiding the output on windows and then printing it?
Or something like that?

**Comment by pfmoore** [comment]
You could probably just use the encoding argument to `run()`.
