### ISSUE TITLE
Does Invoke currently support parallel task execution?

### ISSUE THREAD

**Issue by kmatt** [pyinvoke/invoke#614]
From http://www.pyinvoke.org:

    Like many of its predecessors, it offers advanced features as well – namespacing, task aliasing, before/after hooks, parallel execution and more.

Currently it appears a task with multiple pre tasks will execute those serially. Can those be executed concurrently?

```python
import time
from invoke import task

@task
def one(c):
    print("one start")
    time.sleep(5)
    print("one end")

@task
def two(c):
    print("two start")
    time.sleep(5)
    print("two end")

@task
def three(c):
    print("three start")
    time.sleep(5)
    print("three end")

@task(pre=[one, two, three])
def start(c):
    print("start")
```

```
$ time invoke start
one start
one end
two start
two end
three start
three end
start

real	0m15.235s
```

**Comment by haydenflinner** [comment]
There isn't one that I know of in Invoke itself, but there was one in Fabric 1 (not yet in Fabric 2). I don't think it would take too long to hack together what you want yourself, though. Check out executor.py `def execute`, and maybe the old parallel executor code from Fabric 1.
