### ISSUE TITLE
Slow tab completion

### ISSUE THREAD

**Issue by kuba-lilz** [pyinvoke/invoke#621]
I have a codebase of slightly over 3.5 kloc of Python and using invoke's autocompletion (for bash shell) is disappointingly  slow - about 1 sec per autocompletion.
Usual task for me means a task and an input file, e.g.:
```bash
invoke clean ./configuration/development_config.yaml
```

That would be three autocompletions
- **c**lean
- ./**c**onfiguration
- ./configuration/**d**evelopment_config.yaml

Which takes good 3 seconds to complete.

I benchmarked what parts of code are slow in autocompletion, and ~98% of the time is spent inside `invoke` on importing all the modules.
I might be wrong, but it seems to me the problem here is that as far as I understand when asked for autocompletion, `invoke` scans recursively everything imported inside `tasks.py` - that is not only tasks.py and modules it imports, but also modules those modules import, and so on.

I appreciate that's necessary when actually running the tasks, but for autocompletion only wouldn't it be possible to limit invoke to import only modules that are declared in tasks.py as including tasks? E.g. for tasks.py that looks like this

```python
import myapp.tests
import myapp.whatever

# ... other code

# Add tests tasks
namespace = invoke.Collection(__name__)
namespace.add_collection(myapp.tests, name="tests")
```

it's fair to say that we don't need to import `myapp.whatever` for the purpose of autocompletion.

One could say that if someone imports default collection/namespace inside some arbitrary module imported in tasks, invoke wouldn't know without scanning it. If you want to keep that edge case, an option to explicitly tell invoke to only scan modules that have been annotated for scanning for purpose of autocompletion would be a way out. Something like

```python
invoke.options.autocompletion_modules([myapp.tests])
```
Without above `invoke` would keep its default import everything approach, with above it would limit imports to those specified.

Cutting down on imports unnecessary for autocompletion would speed `invoke` autocompletion a lot.

**Comment by florisla** [comment]
Invoke does not control how Python's import statements work.

I you want to avoid delays due to `import myapp.whatever`, then you can move that import statement to the body of a function (close to where `myapp.whatever` is needed).  This is called lazy loading -- it delays the import to the moment that function is actually called.

**Comment by kuba-lilz** [comment]
Huh, didn't realize imports would be read lazily.
A little bit ugly if a few tasks need same import, but hey, it indeed does work :)

**Comment by florisla** [comment]
Great, don't forget to close this issue then!
