### ISSUE TITLE
Running all sub tasks in one collection

### ISSUE THREAD

**Issue by hokreb** [pyinvoke/invoke#633]
Is it possible to run all tasks of a collection?

Say I a have a collection like

```
build.prog.text
build.prog.create
build.prog.sum
```

If i run 

`invoke build.prog
`
all three tasks text, create and sum will be run.

This would make it very easy to setup a nested tasks system within a nested project directory. If you have a nested project directory with the three "sub" programs text, create and sum, you could place easily for each subproject one task.py file to build only one, and create a in the higher directory level on tasks.py, which import the tasks from the subdirectories to create collection and can easily call a collection to build all programs.

**Comment by florisla** [comment]
You can add the three tasks as "pre-tasks" to `build.prog`.
http://docs.pyinvoke.org/en/1.2/getting-started.html#declaring-pre-tasks

**Comment by hokreb** [comment]
oh man perfect, thats all I need. I didn't realize this feature before, thanks a lot
