### ISSUE TITLE
Documenting parameters with underscore does not work

### ISSUE THREAD

**Issue by mrh1997** [pyinvoke/invoke#668]
If I want add a help text to a parameter with underscore, it will not be displayed. I.e.:
```python
@task(help={'param_with_underscore': "This help text is not shown on inv --help cmd."})
def cmd(c, param_with_underscore):
    pass
```
will produce (note that the help text of "param_with_underscore" is not displayed):
```
>invoke --help cmd
Usage: inv[oke] [--core-opts] cmd [--options] [other tasks here ...]

Docstring:
  none

Options:
  -p STRING, --param-with-underscore=STRING
```

**Comment by GhostLyrics** [comment]
Parameters with underscores in it will be rewritten to have hyphens instead. 
The following snippet will display the help text like you want.
```python
@task(help={'param-with-underscore': "This help text is not shown on inv --help cmd."})
```

**Comment by mrh1997** [comment]
Thx!
Maybe this info should be added to the documentation of the "help" parameter.
