### ISSUE TITLE
Concern with the large number of open pull requests

### ISSUE THREAD

**Issue by nyurik** [pyinvoke/invoke#674]
Hi, I see there are 64 open pull requests (36% of all), which seems rather high.  Is there a way they can be labeled to indicate why they are not being merged, i.e. `work in progress`, `stale`, `rejected`, etc.  I am concerned that people will see this as an indicator that project maintainer(s) do not want to accept any PRs, or that the project is running inactive, and may need more maintainers.  Hope this is not the case, as I see a huge value in this approach.  Thanks for an awesome tool!

**Comment by florisla** [comment]
I'd also love to see a perspective on the future of this great tool.

Is there anything we can do to lower the burden?

**Comment by bitprophet** [comment]
http://bitprophet.org/blog/2020/07/02/help-wanted/ !
