### ISSUE TITLE
DeprecationWarning on usage of imp in loader.py

### ISSUE THREAD

**Issue by milliams** [pyinvoke/invoke#675]
When running my test suite which uses invoke (via fabric) I see:

```
======================= warnings summary ========================
venv/lib64/python3.7/site-packages/invoke/loader.py:3
  venv/lib64/python3.7/site-packages/invoke/loader.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========== 6 passed, 1 warnings in 1651.00s (0:27:30) ===========
```

The used parts of the `imp` module have been deprecated since Python 3.3 and the replacement `importlib` has been available since Python 3.1.

**Comment by SwampFalc** [comment]
For what it's worth, there's a workaround that will suppress that one particular warning. I use it on pytest but I believe it's going to be mostly the same with other test frameworks:

`-W ignore::DeprecationWarning:invoke.loader`

**Comment by rupertnash** [comment]
I have also spotted this - the question is really: which versions of python is invoke committed to supporting? The docs say 2.7 and >=3.4. However, we have now passed 2020-01-01, so the sun has officially gone down on python 2. If I had a vote (which I don't obviously), it would be to drop support for 2.7 and switch this code to `importlib`

Instead I'm adding a warning filter (https://docs.pytest.org/en/latest/warnings.html#pytest-mark-filterwarnings) and have logged an issue on our project.

**Comment by shoriminimoe** [comment]
This issue was brought up again in #829. I would be happy to submit a PR if the team is looking for help.

**Comment by neozenith** [comment]
Hi,
I'm starting to help out on issue triage. Invoke (and the Fabric and Paramiko family) are conservative with the supported versions of python.

But yes, very soon Python2 will be dropped clearing out issues such as this.
https://bitprophet.org/projects/#roadmap

**Comment by MarcSkovMadsen** [comment]
Listening in as I also see this warning.

**Comment by skapin** [comment]
2022, still here ...... :zombie:

**Comment by sodul** [comment]
This will  break in python 3.12:
```
DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
```

May I suggest the use of a conditional import based on the python version? This would address the warnings will ensuring forward compatibility with Python 3.12.

I'm not very fond of silencing the warning since it is very legitimate.

**Comment by kuwv** [comment]
#919

**Comment by bitprophet** [comment]
#919 merged and released in Invoke 2.1.0 today. Thanks!

**Comment by ibc** [comment]
Sorry, what's the status of this? Python 3.12 is out there, for example in macOS 12 runners in GitHub CI. And `invoke` fails to work due to missing `imp` module. Example: https://github.com/versatica/mediasoup/actions/runs/6983152288/job/19003737586

**Comment by kuwv** [comment]
The imp dependency has been replaced. Can you verify what version you are using?

**Comment by ibc** [comment]
> The imp dependency has been replaced. Can you verify what version you are using?

My fault, sorry, I thought I was using latest version but due to a typo I was using 2.0.0, that's why I have deleted my comment.
