### ISSUE TITLE
How do I run Windows programs with spaces in the path and command line arguments?

### ISSUE THREAD

**Issue by alanbowman** [pyinvoke/invoke#676]
I am using Invoke on Windows, and trying to use `run` to execute programs that have spaces in the pathname and take command line arguments.  Something like the following example:
```python
@task
def wireshark(c):
  # cmd = os.path.join( "C:\\", "Program Files", "Wireshark", "wireshark.exe --help" )
  cmd = os.path.join( "C:\\", "Program Files", "Wireshark", "wireshark.exe" )
  c.run(cmd)
```
I've tried numerous ways to get the `--help` on the end of the command, but each attempt seems to end in `'C:\Program' is not recognized as an internal or external command,
operable program or batch file.`  What is the right way to do this?  My example seems to work fine in cases where there are no spaces in the path.

**Comment by florisla** [comment]
The trick is to enclose the paths in double quotes.  Use single quotes to construct the string.

When in doubt, first try you command in a `cmd.exe` Windows console to check where quotes are required.

```#!python
  # with f-strings
  c.run(f'"{cmd}"')
  # without f-strings
  c.run('"' + cmd + '"')
```

**Comment by alanbowman** [comment]
Thanks for the suggestion, but I get the following error with both of your suggestions, under both Command Prompt and Powershell:

> '"C:\Program Files\Wireshark\wireshark.exe --help"' is not recognized as an internal or external command,
> operable program or batch file.
> 

I copy-n-pasted your run commands from Github - is it possible the formatting has been mangled?

**Comment by alanbowman** [comment]
I've just understood what you meant.  The version of my example that works:
```python
@task
def wireshark(c):
  # cmd = os.path.join( "C:\\", "Program Files", "Wireshark", "wireshark.exe --help" )
  cmd = os.path.join( "C:\\", "Program Files", "Wireshark", "wireshark.exe" )
  c.run('"' + cmd + '" --help')
```
