### ISSUE TITLE
Consider option for disabling .pyc generation

### ISSUE THREAD

**Issue by brejoc** [pyinvoke/invoke#68]
Might be nicer of invoke to not generate a tasks.pyc.

**Comment by brutus** [comment]
This sounds pretty neat. What's the state of this and <https://github.com/pyinvoke/invoke/commit/ea9321821bd59976179ef212450357e31892667a>?

**Comment by bitprophet** [comment]
Is that commit part of an actual PR somewhere? If it is, github's not telling me.

**Comment by brutus** [comment]
I just tired it again here: https://github.com/brutus/invoke/commit/e4240746404efbc1083bb12aa3f3f9c64c7ecb06

It still works for me. Just had a quick look though. The test run fine expect one that fails on the additional `--write-pyc` option in the help output as expected.

**Comment by bitprophet** [comment]
Implemented, finally. Thanks again @brutus!
