### ISSUE TITLE
Task can't be used on wrapped functions

### ISSUE THREAD

**Issue by cajopa** [pyinvoke/invoke#684]
Example code:
```python3
from functools import wraps
from invoke import Task

def somewrapper(**kwargs):
    def inner(f):
        @wraps(f)
        def wrapper(c, *a, **kw):
            return f(c, *a, **kw)
        return Task(wrapper, **kwargs)
    return inner

@somewrapper()
def mytask(c, arg1, kwarg1=None):
    pass
```

Expected: `invoke mytask --help` lists arg1 and kwarg1 as options
Actual: `invoke mytask --help` lists no options

I have traced this to `Task.argspec` using `inspect.getargspec`, which does not automatically look for a `__wrapped__` property. I have produced a tiny change that should rectify this (PR to follow). As a point of note, `inspect.getargspec` has been [deprecated](https://docs.python.org/3.7/library/inspect.html#inspect.getargspec) since Python 3.0, in favor of `inpect.signature`, which _does_ automatically look for `__wrapped__`.

**Comment by cajopa** [comment]
https://github.com/pyinvoke/invoke/pull/685

**Comment by tomdottom** [comment]
@cajopa a quick work around for this is to preserve the signature of the wrapped function by adding a `__signature__` attribute:

```python
import inspect
from functools import wraps
from invoke import Task

def somewrapper(**kwargs):
    def inner(f):
        @wraps(f)
        def wrapper(c, *a, **kw):
            return f(c, *a, **kw)
        wrapper.__signature__ = inspect.signature(f)
        return Task(wrapper, **kwargs)
    return inner

@somewrapper()
def mytask(c, arg1, kwarg1=None):
    pass
```

**Comment by bitprophet** [comment]
2.0.0 will be out soon & is now using `inspect.signature`!
