### ISSUE TITLE
Update vendored yaml

### ISSUE THREAD

**Issue by Yajo** [pyinvoke/invoke#708]
I'm using `invoke.utils.yaml` to parse another yaml file in an invoke task, and act according to what's found in it.

That file happens to include emojis, and thus https://stackoverflow.com/a/44875476/1468388 suggests to update to pyyaml>=5 to get rid of that bug.

Also there's a workaround in https://stackoverflow.com/a/44875714/1468388.

I noticed your vendored  pyyaml packages are 6 years old; you should upgrade anyway.

BTW... have you considered using git modules for vendored packages?

**Comment by Yajo** [comment]
I'm having an even better idea:

1. Remove all vendored code.
1. Support installation through [`pipx`](https://pipxproject.github.io/pipx/) only (Py3 only)

Py2 is today unsupported, so it doesn't seem a big deal. With this, you could forget about vendored code and lib conflicts forever in just 1 shot.

You can also use https://python-poetry.org/ to handle dependencies and all should be handled good automatically.

**Comment by jrabbit** [comment]
Ideally most vendored code could be removed unless patches are needed.

**Comment by bitprophet** [comment]
Moving discussion to #803
