### ISSUE TITLE
Be able to configure dynamically the application

### ISSUE THREAD

**Issue by lyrixx** [pyinvoke/invoke#712]
Hello.

I'm trying to update this [project](https://github.com/jolicode/docker-starter) from frabic to invoke.

But I'm facing an issue with [this part](https://github.com/jolicode/docker-starter/blob/master/fabfile.py#L239-L275) of the code where we configure dynamically fabric according to the user platform (user id, os, docker env, etc)

I see I can put a `invoke.py` file next to the `tasks.py`, but If I do that, I'll not be able to use a `invoke.yaml` :grimacing: 

I also tried many thing in the `tasks.py` without success. 

So I have 2 questions:

* Am I doing something wrong?
* If not, Is it possible to look for all format of `invoke.yaml`?

**Comment by pyhedgehog** [comment]
As far as I know `invoke.py` takes precedence over `invoke.yaml`, but you can import it in `invoke.py` explicitly.
