### ISSUE TITLE
Inherit task options

### ISSUE THREAD

**Issue by uael** [pyinvoke/invoke#714]
Is there any possibility to inherit options from another task when using pre/post ?

**Comment by pyhedgehog** [comment]
This idea violates [Zen#2](https://zen-of-python.info/explicit-is-better-than-implicit.html#2).
This can be implemented in three fashions:
1. Pass to task all parameters with same names. This will lead in incorrect values for parameters with same names but different meanings: think of `build(target)`, `mkdir(target)` and `site_deploy(target)`.
2. Save parameters to top-called task to context. It this case you should write in pre-task some complicated code to choose where to get option value from.
3. Some additional syntax to pass exactly specified options to pre/post task. This has no advantage over explicit call to task function.
