### ISSUE TITLE
set GPU CUDA environmental variable

### ISSUE THREAD

**Issue by smilesun** [pyinvoke/invoke#717]
I tried the following code to set the environmental variable `CUDA_VISIBLE_DEVICES`, but it seems that it does not work. 

`invoke fun --cu=1
` still uses the 0th GPU instead of the 1st one.

```
@task
def fun(c, cu):
    c.run("CUDA_VISIBLE_DEVICES="+str(cu))
    import torch
    # run a model
    ....
```

Is there a way to do this correctly?

**Comment by vimalthilak** [comment]
How do you GPU 0 is being used and not GPU 1? can you print the output of ```nvidia-smi```?

**Comment by smilesun** [comment]
it turns out `"CUDA_VISIBLE_DEVICES="+str(cu)` does not work
but `"CUDA_VISIBLE_DEVICES={}"`.format(cu) works.
