### ISSUE TITLE
How can i pass task parameter to one of pre tasks?

### ISSUE THREAD

**Issue by hiphamster** [pyinvoke/invoke#731]
Hi,

This is what i'm trying to achieve, this clearly does not work, but perhaps there's a workaround:

~~~python
@task
def task1(c, config_file):
  # do smth here 
  pass

@task(pre=[call(task1, config_file=config_file)])
def task2(c, config_file):
   # do smth here
   pass
~~~

When running, i'd like to pass the 'config-file' to taks2, and that same value to be passed to task1

Thanks,

Alex

**Comment by miso-belica** [comment]
I think you can simply run the task as a regular function. I understood why the pre-tasks were in the Fabric v1 but from the time the tasks have explicit context, I think it is duplication and you can do this thee easy way.

```python
@task
def task1(c, config_file):
  # do smth here 
  pass

@task
def task2(c, config_file):
   task1(c, config_file)
   # do smth here
   pass
```

**Comment by rberger** [comment]
In more complicated scenarios where you have many cumulative  steps, it would be very useful to be able to have the argument passed as a command line argument to a task be passed on to its pre-tasks. That way you could enter in at any level of the cumulative steps.
