### ISSUE TITLE
invoke command not available after installing into Python 3.8.3 on Windows 10

### ISSUE THREAD

**Issue by FilBot3** [pyinvoke/invoke#737]
I just performed a fresh install of Python 3.8 because I thought I was going bonkers. When I installed `pyinvoke` using the command:

```bash
python -m pip install pyinvoke
```

There is no executable named `invoke` available to me. I am looking in these directories now:

* C:\Users\preda\AppData\Local\Programs\Python\Python38\Scripts
* C:\Users\preda\AppData\Local\Programs\Python\Python38

Nothing shows up in these directories for `inovke`.  Is there a new location this should be in, or am I missing something?

**Comment by miso-belica** [comment]
Hi, I guess you should install `invoke` not `pyinvoke`. See http://www.pyinvoke.org/installing.html

**Comment by FilBot3** [comment]
Ugh, you're right. I failed.
