### ISSUE TITLE
Dying?

### ISSUE THREAD

**Issue by StephenCarboni** [pyinvoke/invoke#738]
208 open issues, 76 open pull requests.

Maybe set up an open collective or _something?_

I see issues a few pages back are properly labelled but then that stopped.

**Comment by florisla** [comment]
Please see #674.

**Comment by blakev** [comment]
Yikes.

**Comment by bitprophet** [comment]
It's always ironic how folks post duplicate issues asking why maintainers don't seem to have the bandwidth to keep up with all of the input... 🙃  see #674 (and surely others), and http://bitprophet.org/blog/2020/07/02/help-wanted/ !

**Comment by StephenCarboni** [comment]
@bitprophet Thank you for the response. I suppose I should have searched a bit harder. You can pin tweets, projects that are suffering from lack of "bandwidth," or going through big changes usually do this as a signpost to those coming to the issues list. All the best.
