### ISSUE TITLE
asynchronous=True disables out_stream

### ISSUE THREAD

**Issue by paw-lu** [pyinvoke/invoke#753]
The documentation states that

> Connections to the controlling terminal are disabled, meaning you will not see the subprocess output and it will not respond to your keyboard input - similar to hide=True and in_stream=False (**though explicitly given (out|err|in)_stream file-like objects will still be honored as normal**).

But when I make a simple task:

```python
@invoke.task()
def async(c):
    with open("file.txt", "w") as file:
        c.run("echo 'hey'", out_stream=file, asynchronous=True)
```

I end up with an empty `file.txt` when I set `asynchronous=True`.

Is there something I'm misunderstanding in the docs? I was under the impression that the output of the command would still be captured in the file specified in `out_stream`. Obviously this is not the case.

Thanks for the amazing library, it's one of my favorites!

**Comment by skozlovf** [comment]
Faced the same issue.

`Runner` forces output hiding in 'async' mode: https://github.com/pyinvoke/invoke/blob/55eddc56dcc3ae3ba85f0840cd7b2f55077d3551/invoke/runners.py#L546-L547

Is there reason for this?

**Comment by skozlovf** [comment]
Ok, It's not true. If pass streams in parameters then it works fine - sends output to the streams (v `1.4.1`):

https://github.com/pyinvoke/invoke/blob/55eddc56dcc3ae3ba85f0840cd7b2f55077d3551/invoke/runners.py#L1605-L1608

@paw-lu Your case has few issues:

* `with open(...)` closes the file right after the `c.run(...)` because it runs in async mode.
* Stream must be opened in binary mode - `"wb"`.

So working code would be smth like:

```python

@invoke.task()
def async(c):
    c.run("echo 'hey'", out_stream=open("file.txt", "wb"), asynchronous=True)

```

**Comment by paw-lu** [comment]
> with `open(...)` closes the file right after the `c.run(...)` because it runs in async mode.

Oh! That makes so much sense now that you spell it out! Thanks for the explanation there. Really appreciated.

> Stream must be opened in binary mode - `"wb"`.

Curious—why is that?

**Comment by skozlovf** [comment]
@paw-lu I probably wrong, it's ok to open in non-binary more, data is decoded from bytes to unicode.

See 
https://github.com/pyinvoke/invoke/blob/55eddc56dcc3ae3ba85f0840cd7b2f55077d3551/invoke/runners.py#L720
https://github.com/pyinvoke/invoke/blob/55eddc56dcc3ae3ba85f0840cd7b2f55077d3551/invoke/runners.py#L666
https://github.com/pyinvoke/invoke/blob/55eddc56dcc3ae3ba85f0840cd7b2f55077d3551/invoke/runners.py#L981

**Comment by paw-lu** [comment]
Got it!

Appreciate all the code pointers here, really made it easier to understand.
