### ISSUE TITLE
Project is dead.  Typer the best recommended alternative?

### ISSUE THREAD

**Issue by calben** [pyinvoke/invoke#762]
It should perhaps be added to the docs that this project is dead and that users should move to a system like Typer (https://typer.tiangolo.com/) if they are intending to use Python 3 features.

Thank you for all your work on this library!

**Comment by calben** [comment]
Great to hear!

**Comment by pawamoy** [comment]
I don't understand why you are citing typer, as they don't have the same purposes :confused:

**Comment by calben** [comment]
Thus the question mark.  What do you think would be a better alternative to which to redirect people?  Click?

**Comment by pawamoy** [comment]
Neither typer nor click: they are meant to build command line interfaces, while invoke is a task runner. I'd rather say nox :)

**Comment by kuwv** [comment]
@calben Invoke is a task runner. Click and Typer are CLI parsers.

**Comment by pawamoy** [comment]
Shameless plug: I've developed a task runner similar to invoke, called duty: https://github.com/pawamoy/duty.
It supports running commands as strings, lists of strings, or even Python callable.
