### ISSUE TITLE
Invoke doesn't pick defaults.run.shell from GitHub Workflow config on Windows?

### ISSUE THREAD

**Issue by pawamoy** [pyinvoke/invoke#763]
I'm running commands such as:

```python
context.run("failprint -t 'Running tests' -- pytest src")
```

In a GitHub Workflow CI, in a Windows OS job, I get errors saying the executable cannot be found. Examples:
- https://github.com/pawamoy/failprint/runs/1188726027?check_suite_focus=true
- https://github.com/pawamoy/failprint/runs/1195783231?check_suite_focus=true

I set the default shell to be `bash` with

```yaml
defaults:
  run:
    shell: bash
```

...but it seems that the shell used by invoke when running the command is batch, because the single quotes do not work as expected: the command args are split like if they were `["failprint", "-t", "'Running", "tests'", "--", "pytest", "src"]`, hence the errors we see in the previously mentioned builds.

I don't know what `defaults: run: shell: bash` does, but I was expecting Invoke to use bash and not comspec/cmd/batch.

I've searched the issues and I think the most straight-forward workaround is to reverse the quotes:

```python
context.run('failprint -t "Running tests" -- pytest src')
```

...so the command is correctly split by batch, but I would really prefer actually telling Invoke to use bash instead.

I've tried the following things:

- overriding the COMSPEC env var to the path to bash (`shutil.which("bash")`
- using `shell=shutil.which("bash")` or `shell="bash"` as arguments to `run`

...but none of these worked. Maybe I should try to wrap the path to bash in double-quotes as well?

Any idea on this 😕 ?

**Comment by thebjorn** [comment]
Maybe give the full path (including the .exe extension) to the program you want to use as shell... or... use a windows shell when you're on windows.

**Comment by pawamoy** [comment]
Hi @thebjorn, thanks for your help!

I am allowed to expect that my Windows users will have Git for Windows installed, and therefore a bash.exe installed, so I don't want to use a windows shell on windows (I don't want to write commands in `context.run` that are compatible for both bash and batch).

I tried passing `shell=str(Path(which("bash.exe")))` or `shell=which("bash.exe")` to `context.run`, but it results in `/c: /c: Is a directory`.

**Comment by pawamoy** [comment]
Another workaround that I prefer a bit:

```python
context.run("bash -c \"failprint -t 'Running tests' -- pytest src\"")
```

The process chain is now `make -> bash -> poetry -> invoke -> cmd -> bash -> failprint -> pytest` hahaha 🤣

**Comment by thebjorn** [comment]
Aren't you the author of failprint?  Just make it support windows and you would have `ctx.run('failprint -t "Running tests" -- pytest src')` which would work on both bash and cmd.exe...

**Comment by thebjorn** [comment]
ps: You probably need to quote the path with spaces, or use the 8.3 version, i.e. `shell=r"c:\PROGRA~1\Git\usr\bin\bash.exe"`.

**Comment by pawamoy** [comment]
I am indeed, but the question here is not whether failprint supports Windows or not 🙂 
I demonstrated in the previous comments that `context.run` will fail on Windows if an argument in the command contains a space and is surrounded by single-quotes instead of double-quotes (because single and double quotes are not interpolatable in cmd.exe/batch). It means that, yes, `ctx.run('failprint -t "Running tests" -- pytest src')` works on both bash and cmd.exe, but not `ctx.run("failprint -t 'Running tests' -- pytest src")`!

**Comment by pawamoy** [comment]
I ended up writing my own tool :speak_no_evil: 

I called it [duty](https://github.com/pawamoy/duty), and it's heavily inspired by invoke, so thanks invoke's authors and maintainers!

**Comment by thebjorn** [comment]
Does it support cmd.exe on windows?  ;-)

**Comment by pawamoy** [comment]
It seems to do! I've successfully run it on my Windows 10 workstation and in a Windows job on GitHub Workflow :relaxed:

Commands can be passed as string, as lists of strings, or even as Python callables. It doesn't make any assumption on the shell to use (except on Linux in one case where it will run sh -c cmd).
