### ISSUE TITLE
first impressions ...

### ISSUE THREAD

**Issue by jcw** [pyinvoke/invoke#771]
First off: I'd _love_ to use `inv[oke]` for all my projects. The self-documenting aspect + flexibility is wonderful.

But here's the thing: you find a new exciting project you'd like to check out. You get it from git and want to start looking into it and tinkering with it. It uses this great `inv -l` tool to perform many of the usual dev chores. Fantastic.

Ok, so after downloading the project, I need to install `pyinvoke`. It's Python, cool, let's do `pip3 install pyinvoke`. Hm, not found. Let's try `pip3 install invoke`. Hm again. Scratch head. Never mind, move on, this project is too hard.

Am I missing something? I _happen_ to use macOS, so `brew install invoke` worked out of the box _for me_, but what if you're not on macOS, or don't use homebrew? Is the installation of a reasonably up-to-date pyinvoke really so difficult? If so, doesn't that completely defeat the purpose of this tool?

I'm sorry, I _really_ would love to base all my projects on the `inv[oke]` command. But getting started is a nightmare.

If a recent version of pyinvoke were to be registered on the PyPi site, this hurdle would just vanish, right?

UPDATE: on Ubuntu 20.04, I see that `apt install python3-invoke` will install 1.3.0, so I suppose that's an option.

**Comment by pgpbpadilla** [comment]
My setup is like this:

```bash
-- File: gitRepo/requirements.txt
invoke
...
other dev tools

-- File: gitRepo/setup.sh
#!/usr/bin/env bash

pip install -r requirements.txt
```

This has worked for me for many years and I like the fact that the code documents the use of Invoke by explicitly stating the dependency in the requirements file.

**Comment by jcw** [comment]
Thanks. Yes, it's a nice way to make everything explicit, but my concern is that on some installations the invoke can either not be found, or a very old version from pypi gets installed.

If `pip3 install invoke` or some equivalent incantation "just works" on the most common development distros, then my concerns will be unfounded.

In short: if everything relies on `pyinvoke`, then we really need a rock-solid / quick / no-brainer way to get that tool working.

(I just learned that on arch, `pip install invoke` also gets the latest version just fine)

**Comment by jcw** [comment]
Well, I was wrong - `pip3 install invoke` on Ubuntu 20,04 does give me 1.4.1, not 1.3.0, or something older.
I guess PyPi is no longer the source of this package.

Closing for now (even though the PiPy state remains a bit unfortunate).
