### ISSUE TITLE
(Re-)allow task help dict to contain unused keys

### ISSUE THREAD

**Issue by Allu2** [pyinvoke/invoke#793]
Previously it has been possible to define dictionary with docstring for each argument used in a file, then pass same dict in
 `@task(help=help_dict)` to all tasks with parameters that have same meaning.

This made it possible to document each parameter only once in a single place, rather then document same parameters repeatedly for each task.

This is helpful especially in cases where most tasks in a file do actions based around same concepts.

After https://github.com/pyinvoke/invoke/pull/611 this seems no longer possible, as any task that doesn't use all arguments defined in the `help_dict` will throw an error.

For example if one has tasks `add_album(artist_id, album_id), find_albums(artist_id), find_artist(album_id)` where previously something like:
```python
help_dict = {
    "artist_id": "Identifier for artist or band",
    "album_id": "Identifier for the album (UUIDv4)"
}
```
could be used to all tasks, now `find_albums` and `find_artist` tasks would cause error, since the tasks don't define one of the parameters listed in `help_dict`.

**Comment by bitprophet** [comment]
I have a dayjob-internal report of this as well and it seems like a 100% match to what @Allu2 describes - they have a very large spread of tasks (across 48 repositories!) and centrally define the help dict to share among all of them so they don't have to figure out how to slice it up for each task.

Solving the latter problem at a higher level is still outstanding (I'm sure there are other tickets for this, I just don't have them bookmarked) but this seems like a good fit for a "mea culpa" config option users can flip back to "no I would rather share my help dicts across tasks, at the expense of not being informed when I've made typos in the dict keys".

Needs a look-see at how we inform Task objects with configuration data (I expect somewhere in Program or Collection) but I'm hoping this is possible w/o too much weird stuff.

**Comment by bitprophet** [comment]
New config option added, out in 1.7 tonight 🎉
