### ISSUE TITLE
Invoke is broken for Python 3.10

### ISSUE THREAD

**Issue by davidalo** [pyinvoke/invoke#827]
As I saw in #820, there are more people who are having the same issues with Invoke and Python 3.10. As far as I could see, `invoke` seems to be broken in Python 3.10. It seems that Python has moved some classes from `collections` to `collections.abc`. 
This produces `ImportError` exceptions y some `invoke` features.

To reproduce this issue, you can see #820. In addition to this, I have tried it using `python:3-alpine3.13` docker and adding a simple task. 
The result is similar to #820:

``` 
/ # inv -l
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 5, in <module>
    from invoke.main import program
  File "/usr/local/lib/python3.10/site-packages/invoke/__init__.py", line 2, in <module>
    from .collection import Collection  # noqa
  File "/usr/local/lib/python3.10/site-packages/invoke/collection.py", line 4, in <module>
    from .util import six, Lexicon, helpline
  File "/usr/local/lib/python3.10/site-packages/invoke/util.py", line 1, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

Invoke version:
```
/ # pip show invoke
Name: invoke
Version: 1.6.0
Summary: Pythonic task execution
Home-page: http://docs.pyinvoke.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: BSD
Location: /usr/local/lib/python3.10/site-packages
Requires: 
``` 

I think this can be fixed by checking the Python version before importing elements from collections or using a try/except statement. I can submit a PR if you want.

**Comment by davidalo** [comment]
This is fixed in master version, but we would need a new release to fix them in production.

**Comment by mush42** [comment]
Waiting for the new release!!!!!

**Comment by tuukkamustonen** [comment]
@bitprophet We know your focus is elsewhere these days, but pushing out a new release to support 3.10 would be important. Any plans for that?

**Comment by bitprophet** [comment]
My next focus is overhauling Invoke's CI & metadata, which will naturally lead to another release, so yea, that's coming soon! (see roadmap: https://bitprophet.org/projects#roadmap)

**Comment by bitprophet** [comment]
#803 should hopefully fix this - out ASAP.
