### ISSUE TITLE
Use of `imp` modules should be removed

### ISSUE THREAD

**Issue by jonringer** [pyinvoke/invoke#829]
The `imp` module has been deprecated since python 3.4, and now emits warnings when used in python 3.9.6+.

The logic should be replaced with `importlib`.

Now if this package, or any downstream dependency uses this, pytest deprecation warnings need to be silenced or else it fails a test suite.

**Comment by robbieaverill** [comment]
Duplicate of https://github.com/pyinvoke/invoke/issues/675. There's some context in there for how to disable this deprecation warning in pytest runs.

**Comment by bitprophet** [comment]
#919 merged and released in Invoke 2.1.0 today. Thanks!
