### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

### ISSUE THREAD

**Issue by HacKanCuBa** [pyinvoke/invoke#833]
I'm having an issue running invoke (latest) in Python 3.11-dev (3.11.0a3). For this [tasks file](https://gitlab.com/hackancuba/blake2signer/-/blob/feature/blake3/tasks.py), this is the trace I get:

```
root@18bb2bd21aaa:/b2s# poetry run inv tests
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/bin/inv", line 8, in <module>
    sys.exit(program.run())
             ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 902, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/b2s/tasks.py", line 11, in <module>
    def flake8(ctx):
    ^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/tasks.py", line 325, in task
    return klass(args[0], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/blake2signer-uv6dtlQx-py3.11/lib/python3.11/site-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

It works perfectly fine for any other Python version I tried (3.7, 3.8, 3.9, 3.10, PyPy3.7, PyPy3.8, Stackless3.7, Stackless3.8).

The module `inspect` does indeed not have said attribute, and I see that there's a potential replacement done in [`invoke.vendor.decorator`](https://github.com/pyinvoke/invoke/blob/45dc9d03639dac5b6d1445831bf270e686ef88b4/invoke/vendor/decorator.py#L67-L70) for some reason.

**Comment by ktbarrett** [comment]
I'm getting a similar error in Python 3.10 if I use type annotations. [`inspect.getargspec` was deprecated in 3.0.](https://docs.python.org/3/library/inspect.html?highlight=inspect#inspect.getargspec). After looking at the Python 2 documentation, it seems it doesn't have the suggested replacement `inspect.getfullargspec` nor the more flexible `inspect.signature`. Fixing this is going to involve some version specific code.

**Comment by kasium** [comment]
It seems like invoke is not python 3.11 ready at all

**Comment by emcd** [comment]
Broken against the 3.11 release.

Looks like @bitprophet has been working on [getting rid of Python 2 support](https://bitprophet.org/blog/2021/02/25/byethon2/), which would make fixing this issue easier. That said, I agree with the original poster that a potential fix already exists in `invoke.vendor.decorator`. Seems like the [`invoke.tasks` code](https://github.com/pyinvoke/invoke/blob/77162cd856b86f1254947ec0ca0285ba9d4776c0/invoke/tasks.py#L153) could use the replacement `getargspec` implementation provided in that module and we would have a workaround for the issue.

**Comment by ian-em** [comment]
Until an update is released this can be worked around temporarily with a hack to monkey patch the `inspect` module in your `tasks.py` file. Here is an example working for me on Python 3.11:

```python3

import inspect

if not hasattr('inspect', 'getargspec'):
    inspect.getargspec = inspect.getfullargspec

from invoke import task

@task
def say_hello(c):
    print("Hello, World!")
```

**Comment by manykarim** [comment]
Both PRs below would solve it, right?

https://github.com/pyinvoke/invoke/pull/458
https://github.com/pyinvoke/invoke/pull/606

**Comment by emcd** [comment]
I ended up forking this repo, applying [this commit](https://github.com/emcd/invoke/commit/fb40a3c79b3fa59cb589a642d0c4b8fa87ca082e) to the fork, and then referencing the package as `invoke @ git+https://github.com/emcd/invoke.git@fb40a3c79b3fa59cb589a642d0c4b8fa87ca082e`, which `pip` (and presumably other Python package utilities/systems) can use to build/install the package directly from the repo. Doing this fixed/worked around the Python 3.11 compatibility issue for me.

Others could do likewise with their own forks, if they need to be unblocked. Not a great long-term solution, obviously....

**Comment by janrito** [comment]
This monkeypatch worked for me - adapted from @zelo's in https://github.com/pyinvoke/invoke/pull/606

```python
# type: ignore
from collections import namedtuple
from inspect import getfullargspec
from unittest.mock import patch

import invoke


def fix_annotations():
    """
    Pyinvoke doesn't accept annotations by default, this fix that
    Based on: @zelo's fix in https://github.com/pyinvoke/invoke/pull/606
    Context in: https://github.com/pyinvoke/invoke/issues/357
        Python 3.11 https://github.com/pyinvoke/invoke/issues/833
    """

    ArgSpec = namedtuple("ArgSpec", ["args", "defaults"])

    def patched_inspect_getargspec(func):
        spec = getfullargspec(func)
        return ArgSpec(spec.args, spec.defaults)

    org_task_argspec = invoke.tasks.Task.argspec

    def patched_task_argspec(*args, **kwargs):
        with patch(
            target="inspect.getargspec", new=patched_inspect_getargspec, create=True
        ):
            return org_task_argspec(*args, **kwargs)

    invoke.tasks.Task.argspec = patched_task_argspec

```

**Comment by JonZeolla** [comment]
I think this is fixed by https://github.com/pyinvoke/invoke/commit/406a45e854f6e8df4aa0de01e3b731fea2b1f1ec, we just need a release

**Comment by neozenith** [comment]
Sorry I have been absent from triage duties.. life kind of happened.

If anyone want to beta test branches, patches or commits and provide additional test cases you can use this format:

```sh
pip install https://github.com/pyinvoke/invoke/archive/406a45e854f6e8df4aa0de01e3b731fea2b1f1ec.zip
```

[Stackoverflow: How to pip install from a github branch or commit](https://stackoverflow.com/a/24811490/622276)

**Comment by bitprophet** [comment]
Apologies for the radio silence on here myself! The above fix will get released in 2.0.0 which should be out pretty soon (and which will be backwards **compatible** besides dropping support for Python <3.5).

**Comment by voidus** [comment]
My take on the workaround, with a warning once it becomes unneccessary:

```python
# Work around https://github.com/pyinvoke/invoke/issues/833
try:

    @task
    def ignore_me(c):
        """Only defined to detect an invoke issue, ignore me"""
        pass

except AttributeError as e:
    if e.args != ("module 'inspect' has no attribute 'getargspec'",):
        raise
    import invoke.tasks  # type: ignore

    invoke.tasks.inspect.getargspec = invoke.tasks.inspect.getfullargspec  # type: ignore
else:
    import warnings

    warnings.warn(
        "Please remove unneccessary monkeypatch, invoke works with python311 now"
    )
```

**Comment by HacKanCuBa** [comment]
> > Hasta que se publique una actualización, esto se puede solucionar temporalmente con un truco para parchear el `inspect`módulo en su `tasks.py`archivo. Aquí hay un ejemplo que me funciona en Python 3.11:
> > ```python
> > import inspect
> > 
> > if not hasattr(inspect, 'getargspec'):
> >     inspect.getargspec = inspect.getfullargspec
> > 
> > from invoke import task
> > 
> > @task
> > def say_hello(c):
> >     print("Hello, World!")
> > ```
> 
> it works for me on official Nexus 20, thanks it would be great if it could be put in the next update

it will be in the next release, whenever there is one :)

**Comment by JonZeolla** [comment]
@HacKanCuBa it's already out

https://github.com/pyinvoke/invoke/releases/tag/2.0.0
https://pypi.org/project/invoke/2.0.0/

**Comment by bitprophet** [comment]
Yup, 2.0.0 is out, so if anyone is still getting this error please let us know!

**Comment by barismutanpicus** [comment]
I just tried with invoke=2.0.0 and still getting the same error, here is the traceback:

`Traceback (most recent call last):
  File "/Users/barismutan/yeti/yeti.py", line 7, in <module>
    from core.web import webapp
  File "/Users/barismutan/yeti/core/web/__init__.py", line 1, in <module>
    from core.web.webapp import webapp
  File "/Users/barismutan/yeti/core/web/webapp.py", line 14, in <module>
    from core.web.api import api
  File "/Users/barismutan/yeti/core/web/api/__init__.py", line 1, in <module>
    from core.web.api.api import api
  File "/Users/barismutan/yeti/core/web/api/api.py", line 52, in <module>
    Analysis.register(api)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask_classy.py", line 128, in register
    rule = cls.build_rule("/", value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask_classy.py", line 244, in build_rule
    args = get_true_argspec(method)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask_classy.py", line 297, in get_true_argspec
    argspec = inspect.getargspec(method)
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?`

**Comment by kasium** [comment]
@barismutanpicus seems to be related to flask_class not invoke as you can see in the traceback

**Comment by bitprophet** [comment]
Yup, that's not us this time 😇

**Comment by estatistics** [comment]
`/usr/bin/gnome-language-selector
Traceback (most recent call last):
  File "/usr/bin/gnome-language-selector", line 5, in <module>
    from LanguageSelector.gtk.GtkLanguageSelector import GtkLanguageSelector
  File "/usr/lib/python3/dist-packages/LanguageSelector/gtk/GtkLanguageSelector.py", line 27, in <module>
    import aptdaemon.client
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 54, in <module>
    class AptTransaction(GObject.Object):
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 656, in AptTransaction
    @convert_dbus_exception
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aptdaemon/errors.py", line 177, in convert_dbus_exception
    argnames, varargs, kwargs, defaults = inspect.getargspec(func)`

**Comment by HacKanCuBa** [comment]
> bookworm sid 12 (ubuntu-debian) `/usr/bin/gnome-language-selector Traceback (most recent call last): File "/usr/bin/gnome-language-selector", line 5, in <module> from LanguageSelector.gtk.GtkLanguageSelector import GtkLanguageSelector File "/usr/lib/python3/dist-packages/LanguageSelector/gtk/GtkLanguageSelector.py", line 27, in <module> import aptdaemon.client File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 54, in <module> class AptTransaction(GObject.Object): File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 656, in AptTransaction @convert_dbus_exception ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/aptdaemon/errors.py", line 177, in convert_dbus_exception argnames, varargs, kwargs, defaults = inspect.getargspec(func)`

There's no mention of `invoke` in that trace, I doesn't seem to be related to this package :)
Try on `gnome-language-selector` bug tracker, or [ubuntu's bug tracker](https://bugs.launchpad.net/ubuntu).

BTW, I now feel guilty that this issue's name is attracting a lot of false positives :P
I'm gonna change the title
