### ISSUE TITLE
Fix Nose deprecation warning with Pytest

### ISSUE THREAD

**Issue by kuwv** [pyinvoke/invoke#901]
Pytest had builtin support for nose that is not deprecated in 7.0. The current tests used by invoke utitlize a `setup()` method which Pytest marks as Nose compatibility. Changing this method to `setup_method()` allows the tests to succeed without warnings.

**Comment by kuwv** [comment]
https://github.com/pyinvoke/invoke/pull/903

**Comment by bitprophet** [comment]
Right, and I think I eventually updated pytest-relaxed to account for `setup_method` style setups too. If I'm right about that, this shouldn't be a problem. Let's roll this into the PR.
