### ISSUE TITLE
invoke 2.0.0 fails to properly cleanup timer on runner

### ISSUE THREAD

**Issue by puerkito66** [pyinvoke/invoke#910]
Following the commit history looks like https://github.com/pyinvoke/invoke/commit/87d337084b20640a3e00bf810b769eaa73f58e8e is the root cause of https://github.com/fabric/fabric/issues/2241

`Local` runner is not calling their parent `stop()` but it's calling it's propper `stop()` method, thus making the timer thread is never cancelled.

According to [this commnet](https://github.com/pyinvoke/invoke/commit/87d337084b20640a3e00bf810b769eaa73f58e8e#diff-ccaafbd8e422ff11f4910b2ebc88a52f5918b50dea641324d446d730db14c83bL1152) calling the parent `stop()`  should solve this problem. 

https://github.com/pyinvoke/invoke/blob/7184e16d8c27f3fd92b2e9f3c3059c41c0366472/invoke/runners.py#L1330-L1340

**Comment by bitprophet** [comment]
Thanks for the report, just pushed a fix and will release shortly.
